### ISSUE TITLE
English Version

### ISSUE THREAD

**Issue by simhaonline** [cym1102/nginxWebUI#1]
Hi,

Do you have option to change Language to English, can you please advice me.

Regards,

Mehulkumar Bhatt

**Comment by cym1102** [comment]
Give&nbsp;me&nbsp;some&nbsp;time,&nbsp;I&nbsp;will&nbsp;give&nbsp;a&nbsp;language&nbsp;choice&nbsp;to&nbsp;English.&nbsp;


cym1102&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Simha.Online"<notifications@github.com&gt;; 
发送时间: 2020年8月4日(星期二) 上午9:08
收件人: "cym1102/nginxWebUI"<nginxWebUI@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [cym1102/nginxWebUI] English Version (#1)





 
Hi,
 
Do you have option to change Language to English, can you please advice me.
 
Regards,
 
Mehulkumar Bhatt

**Comment by simhaonline** [comment]
Thank you, will be waiting to get update from you

**Comment by cym1102** [comment]
now version 1.8.2 add English language
