### ISSUE TITLE
为什么docker形式部署要以privileged模式启动？

### ISSUE THREAD

**Issue by AnxysUaen** [cym1102/nginxWebUI#103]

**Comment by cym1102** [comment]
因为要用chmod命令



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月31日(周四) 下午5:33
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cym1102/nginxWebUI] 为什么docker要以privileged模式启动？ (Issue #103)

**Comment by AnxysUaen** [comment]
> 

感谢回复

请问为什么会涉及到修改宿主机的文件呢？
另：如果nginx只在容器间代理的话，是否就不需要特权模式了呢。

**Comment by cym1102** [comment]
主要是集成的acme.sh需要执行权限



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月31日(周四) 晚上6:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cym1102/nginxWebUI] 为什么docker形式部署要以privileged模式启动？ (Issue #103)




   
感谢回复
 
请问为什么会涉及到修改宿主机的文件呢？
 另：如果nginx只在容器间代理的话，是否就不需要特权模式了呢。

**Comment by AnxysUaen** [comment]
生成证书后需要存储在volume内，然后需要修改ssl证书的权限，但是docker的volume不允许进行chmod操作。所以才需要特权模式？
不知道我理解的是不是对的。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年08月31日 18:04 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [cym1102/nginxWebUI] 为什么docker形式部署要以privileged模式启动？ (Issue #103) |

主要是集成的acme.sh需要执行权限



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月31日(周四) 晚上6:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cym1102/nginxWebUI] 为什么docker形式部署要以privileged模式启动？ (Issue #103)





感谢回复

请问为什么会涉及到修改宿主机的文件呢？
另：如果nginx只在容器间代理的话，是否就不需要特权模式了呢。
