### ISSUE TITLE
反向代理不生效

### ISSUE THREAD

**Issue by xixihebei** [cym1102/nginxWebUI#106]
家用公网ip,无80  443端口。

开放800->nginxWebUi端口。

想根据不同的域名反向代理不同的服务器，现象：打开的页面都是nginxWebUi页面。

本地服务：http://192.168.0.130:19999/auth/login
![image](https://github.com/cym1102/nginxWebUI/assets/145092658/15011d05-cec0-47cf-9fe1-8e321cf9b0bd)

希望通过nginx 800  反向代理到192.168.0.130:19999/
具体配置
![image](https://github.com/cym1102/nginxWebUI/assets/145092658/e0990113-6c38-4011-870f-24b0f73a453d)

结果：
![image](https://github.com/cym1102/nginxWebUI/assets/145092658/703a55f9-ba50-433c-960d-0efd862abe65)

不知道什么原因导致的

**Comment by cym1102** [comment]
不清楚问题所在




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cym1102/nginxWebUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月28日(星期四) 下午3:06
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[cym1102/nginxWebUI] 反向代理不生效 (Issue #106)





 
家用公网ip,无80  443端口。
 
开放800-&gt;nginxWebUi端口。
 
想根据不同的域名反向代理不同的服务器，现象：打开的页面都是nginxWebUi页面。
 
本地服务：http://192.168.0.130:19999/auth/login
 
 
希望通过nginx 800  反向代理到192.168.0.130:19999/
 具体配置
 
 
结果：
 
 
不知道什么原因导致的

**Comment by wlclass** [comment]
800端口是你的nginxWebUi的管理端口.冲突了.
