### ISSUE TITLE
前端网页乱码

### ISSUE THREAD

**Issue by XYZliang** [cym1102/nginxWebUI#107]
如题，系统用的不多，以前好像也出过这个情况：
<img width="1008" alt="image" src="https://github.com/cym1102/nginxWebUI/assets/59312540/53b3c48e-dd6d-46ba-bbe1-21c7539c8254">
似乎前端代码不知道为什么乱了
<img width="391" alt="image" src="https://github.com/cym1102/nginxWebUI/assets/59312540/f653b356-7b07-4aec-b4e3-7d69994c09e1">
异常显示的内容是：
`
overall type: UNKNOWN_TYPE
server type: NO_SERVER_DATA
heuristic type: UNKNOWN_TYPE
ml type: NO_SERVER_DATA
raw ml type: NO_SERVER_DATA
label: ssl协议版本
parseable name: TLSv1
section: proxyType_0_2890
field signature: 1688624352
form signature: 12541816395556328331
form signature in host form: 12541816395556328331
alternative form signature: 2261659641184365213
field frame token: B2C31FDBDD26883E9BD58409FA870F14
form renderer id: 108
field renderer id: 2907
visible: false
focusable: false
field rank: 15
field rank in signature group: 0
field rank in host form: 15
field rank in host form signature group: 0
field signature string: TLSv1&checkbox
form signature string: 
form order: RegularForm1
field order: -1
form signatureV2: -7751986570996893221
field signatureV2: -7329687746762499336
domain signature: 961732116166736513
c id: 961732116166736513|$|978518217896419571|$|-9216432302443112677
block suggestion reasons: None
autocomplete: off
`
环境是3.6.9的docker，在控制台点了升级到最新的3.7.5。

**Comment by cym1102** [comment]
是你防火墙根据关键字进行了阻拦吧

**Comment by XYZliang** [comment]
> 是你防火墙根据关键字进行了阻拦吧

没有任何的防火墙。
另外为什么总是没了解完没解决完问题就要关闭 issues？每次提交反馈都没有结果

**Comment by cym1102** [comment]
因为我有点强迫症, 不关闭issue我就不舒服, 如果可以的话, 你进qq群反馈要快很多



***@***.***
 
发件人： XYZliang
发送时间： 2023-11-27 01:43
收件人： cym1102/nginxWebUI
抄送： cym1102; State change
主题： Re: [cym1102/nginxWebUI] 前端网页乱码 (Issue #107)
是你防火墙根据关键字进行了阻拦吧
没有任何的防火墙。
另外为什么总是没了解完没解决完问题就要关闭 issues？每次提交反馈都没有结果
