### ISSUE TITLE
啟用配置內的生成配置文件沒有正確載入

### ISSUE THREAD

**Issue by unchannam** [cym1102/nginxWebUI#108]
在左邊的生成配置文件文字框內加入配置指令, 按"校驗文件"校驗後是有儲存到temp/nginx.conf內, 但是重新載入網頁後, 左邊的生成配置文件文字框還是顯示之前沒有修改過的版本. 

使用版本: 3.7.6

**Comment by cym1102** [comment]
那个编辑功能本来就是给你临时用的，真正要保存编辑的数据，你得用模板功能配置到每个实体项目上



---原始邮件---
发件人: "Ronald ***@***.***&gt;
发送时间: 2023年10月26日(周四) 上午8:55
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cym1102/nginxWebUI] 啟用配置內的生成配置文件沒有正確載入 (Issue #108)




 
在左邊的生成配置文件文字框內加入配置指令, 按"校驗文件"校驗後是有儲存到temp/nginx.conf內, 但是重新載入網頁後, 左邊的生成配置文件文字框還是顯示之前沒有修改過的版本.
 
使用版本: 3.7.6

**Comment by unchannam** [comment]
了解，謝謝。

在 2023年10月26日週四 上午9:26，cym1102 ***@***.***> 寫道：
