### ISSUE TITLE
UnknownHostException: www.nginxwebui.cn

### ISSUE THREAD

**Issue by wangxm345566462** [cym1102/nginxWebUI#11]
离线环境无法访问。

**Comment by cym1102** [comment]
那个是更新程序, 不要紧的, 访问不了一般是防火墙没有关




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cym1102/nginxWebUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月16日(星期五) 下午4:32
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[cym1102/nginxWebUI] UnknownHostException: www.nginxwebui.cn (#11)





 
离线环境无法访问。

**Comment by wangxm345566462** [comment]
如果访问不了 ， 项目将无法正常启动访问。 Version 并未初始化。  堆栈  com.cym.NginxWebUI.main(:38)

**Comment by cym1102** [comment]
这边测过了, 没有网络可以正常启动




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月16日(星期五) 下午4:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cym1102/nginxWebUI] UnknownHostException: www.nginxwebui.cn (#11)





 
如果访问不了 ， 项目将无法正常启动访问。 Version 并未初始化。  堆栈  com.cym.NginxWebUI.main(:38)

**Comment by wangxm345566462** [comment]
源码我刚下载，确实没有问题，docker 模式下有问题

cym1102/nginxwebui:2.5.5

![Uploading image.png…]()
![Uploading image.png…]()

**Comment by cym1102** [comment]
好，我到时候看看



---Original---
From: ***@***.***&gt;
Date: Fri, Apr 16, 2021 17:25 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cym1102/nginxWebUI] UnknownHostException: www.nginxwebui.cn (#11)




 
源码我刚下载，确实没有问题，docker 模式下有问题
 
cym1102/nginxwebui:2.5.5

**Comment by wangxm345566462** [comment]
3Q . 目前 配置了一个 nginx 把 json 重新加了下。好了
