### ISSUE TITLE
监听ipv6并且启用http转https时会出错

### ISSUE THREAD

**Issue by Gahon1995** [cym1102/nginxWebUI#110]
生成的301redirect的port识别有问题

**Comment by cym1102** [comment]
可以自己用额外参数实现return 301




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月9日(星期四) 中午11:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [cym1102/nginxWebUI] 监听ipv6并且启用http转https时会出错 (Issue #110)





 
生成的301redirect的port识别有问题
