### ISSUE TITLE
关于远程服务器管理的问题

### ISSUE THREAD

**Issue by xplainn** [cym1102/nginxWebUI#112]
能否在合适的地方添加一项，该服务器的选中状态是“选中”还是“未选中”，这样更加容易区分当前选中的服务器是哪一台。
![屏幕截图 2023-11-17 101046](https://github.com/cym1102/nginxWebUI/assets/22995563/e9088c87-6832-4c72-8c75-afa23cc26c9d)

**Comment by cym1102** [comment]
可以




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月17日(星期五) 上午10:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [cym1102/nginxWebUI] 关于远程服务器管理的问题 (Issue #112)





 
能否在合适的地方添加一项，该服务器的选中状态是“选中”还是“未选中”，这样更加容易区分当前选中的服务器是哪一台。
