### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by Fw-fW-fw** [cym1102/nginxWebUI#113]
## 0x01 File upload

Interface：/adminPage/main/upload

com/cym/controller/adminPage/MainController.java#upload

```java
	@Mapping("/adminPage/main/upload")
	public JsonResult upload(Context context, UploadedFile file) {
		try {
			File temp = new File(FileUtil.getTmpDir() + "/" + file.getName());
			file.transferTo(temp);

			return renderSuccess(temp.getPath().replace("\\", "/"));
		} catch (IllegalStateException | IOException e) {
			logger.error(e.getMessage(), e);
		}

		return renderError();
	}
```

You can see that file.getName () is not filtered, causing the.. /.. / directory to traverse to the ssh directory, there is no restriction on the suffix name, and you can write the public key to get shell. 
Then replace the path "/".

##  Reappearance

ssh-keygen -t rsa -f id_rsa

upload.

![image](https://github.com/cym1102/nginxWebUI/assets/66824584/4e5d88eb-2105-4b00-932c-a6d394305891)

You can see the successful upload
![image](https://github.com/cym1102/nginxWebUI/assets/66824584/db6e7884-e144-4ac2-b043-bb37b1f32d54)

Success

**Comment by cym1102** [comment]
ok, I will fix this
