### ISSUE TITLE
手机浏览器或较小pc屏幕无法看到service的添加代理目标按钮

### ISSUE THREAD

**Issue by karthrand** [cym1102/nginxWebUI#114]
![nginxwebui-1.webp](https://img.oudezhinu.com/img/1/nginxwebui-1.webp)
![nginxwebui-2.webp](https://img.oudezhinu.com/img/1/nginxwebui-2.webp)

反向代理界面，添加或者编辑反向代理
在手机浏览器或者较小的pc屏幕上，【添加代理目标(Location)】这个按钮无法查看到
手机上无论是切换浏览器模式还是横屏之类都看不到

**Comment by cym1102** [comment]
好, 我尝试解决一下这个问题



***@***.***
 
发件人： 欧德之怒
发送时间： 2023-11-22 21:38
收件人： cym1102/nginxWebUI
抄送： Subscribed
主题： [cym1102/nginxWebUI] 浏览器或较小屏幕无法看到service的添加代理目标按钮 (Issue #114)

反向代理界面，添加或者编辑反向代理
在手机浏览器或者较小的pc屏幕上，【添加代理目标(Location)】这个按钮无法查看到
手机上无论是切换浏览器模式还是横屏之类都看不到

**Comment by karthrand** [comment]
赞，3.7.9最新版确认已解决
