### ISSUE TITLE
Arbitrary file deletion 

### ISSUE THREAD

**Issue by Fw-fW-fw** [cym1102/nginxWebUI#115]
com/cym/controller/adminPage/ExportController.java#dataImport()

```java
@Mapping(value = "dataImport")
public void dataImport(UploadedFile file, Context context) throws IOException {
   if (file != null) {
      File tempFile = new File(homeConfig.home + "temp" + File.separator + file.getName());
      FileUtil.mkdir(tempFile.getParentFile());
      file.transferTo(tempFile);
      String json = FileUtil.readString(tempFile, StandardCharsets.UTF_8);
      tempFile.delete();

      AsycPack asycPack = JSONUtil.toBean(json, AsycPack.class);
      confService.setAsycPack(asycPack);
      
      // 导入证书
      if (asycPack.getCertList() != null) {
         sqlHelper.deleteByQuery(new ConditionAndWrapper(), Cert.class);
         sqlHelper.insertAll(asycPack.getCertList());
      }
      if (asycPack.getCertCodeList() != null) {
         sqlHelper.deleteByQuery(new ConditionAndWrapper(), CertCode.class);
         sqlHelper.insertAll(asycPack.getCertCodeList());
      }
      
      certService.writeAcmeZipBase64(asycPack.getAcmeZip());
   }
   context.redirect("/adminPage/export?over=true");
}
```

 You can see that file.getName() has no filtering, resulting in../../  Directory traversal also has no restrictions on suffix names. It uploads files first, then reads them from inside, and then deletes files. As long as the control of the incoming file name causes any file to be deleted. 

### test

![image](https://github.com/cym1102/nginxWebUI/assets/66824584/838d8b98-5bf0-4df7-b26d-19bfaf972c11)

 Create hookdd 

 Construct data packets 

![image](https://github.com/cym1102/nginxWebUI/assets/66824584/84ad260b-25d8-4fce-b7c1-ca1cbb4a0075)
![image](https://github.com/cym1102/nginxWebUI/assets/66824584/c2e92e77-44b4-49a4-b9ca-88f0c859c96d)

completed the delete

**Comment by Fw-fW-fw** [comment]
![image](https://github.com/cym1102/nginxWebUI/assets/66824584/1510ccbb-ba46-4f33-946a-cd05f1b72df4)
 /r/n Delete here/r

**Comment by cym1102** [comment]
OK



***@***.***
 
From: jason
Date: 2023-11-23 04:16
To: cym1102/nginxWebUI
CC: Subscribed
Subject: [cym1102/nginxWebUI] Arbitrary file deletion (Issue #115)
com/cym/controller/adminPage/ExportController.java#dataImport()
@Mapping(value = "dataImport")
public void dataImport(UploadedFile file, Context context) throws IOException {
   if (file != null) {
      File tempFile = new File(homeConfig.home + "temp" + File.separator + file.getName());
      FileUtil.mkdir(tempFile.getParentFile());
      file.transferTo(tempFile);
      String json = FileUtil.readString(tempFile, StandardCharsets.UTF_8);
      tempFile.delete();
      AsycPack asycPack = JSONUtil.toBean(json, AsycPack.class);
      confService.setAsycPack(asycPack);
      
      // 导入证书
      if (asycPack.getCertList() != null) {
         sqlHelper.deleteByQuery(new ConditionAndWrapper(), Cert.class);
         sqlHelper.insertAll(asycPack.getCertList());
      }
      if (asycPack.getCertCodeList() != null) {
         sqlHelper.deleteByQuery(new ConditionAndWrapper(), CertCode.class);
         sqlHelper.insertAll(asycPack.getCertCodeList());
      }
      
      certService.writeAcmeZipBase64(asycPack.getAcmeZip());
   }
   context.redirect("/adminPage/export?over=true");
}
You can see that file.getName() has no filtering, resulting in../../ Directory traversal also has no restrictions on suffix names. It uploads files first, then reads them from inside, and then deletes files. As long as the control of the incoming file name causes any file to be deleted.
test
Create hookdd
Construct data packets

completed the delete
