### ISSUE TITLE
Admin 类型可注入autoKey绕过认证

### ISSUE THREAD

**Issue by Fw-fW-fw** [cym1102/nginxWebUI#116]
com/cym/controller/adminPage/AdminController.java#changePassOver()

```java
	@Mapping("changePassOver")
	public JsonResult changePassOver(Admin admin) {

		adminService.changePassOver(admin);

		return renderSuccess();
	}
```

```java
	public void changePassOver(Admin admin) {
		if (admin.getAuth()) {
			Admin adminOrg = sqlHelper.findById(admin.getId(), Admin.class);
			if (StrUtil.isEmpty(adminOrg.getKey())) {
				admin.setKey(authUtils.makeKey());
			}
		} else {
			admin.setKey("");
		}

		if (StrUtil.isNotEmpty(admin.getPass())) {
			admin.setPass(EncodePassUtils.encode(admin.getPass()));
		} else {
			admin.setPass(null);
		}
		sqlHelper.updateById(admin);

	}
```

这里也是对admin.getId()判断，然后来改密码。

com/cym/controller/adminPage/AdminController.java

```java
	@Mapping("addOver")
	public JsonResult addOver(Admin admin, String[] parentId) {
		if (StrUtil.isEmpty(admin.getId())) {
			Long count = adminService.getCountByName(admin.getName());
			if (count > 0) {
				return renderError(m.get("adminStr.nameRepetition"));
			}
		} else {
			Long count = adminService.getCountByNameWithOutId(admin.getName(), admin.getId());
			if (count > 0) {
				return renderError(m.get("adminStr.nameRepetition"));
			}
		}

		adminService.addOver(admin, parentId);

		return renderSuccess();
	}
```

添加用户的路由, 可以控制admin，parentId，admin.getId()是否为空，不为空进入adminService.getCountByName，跟进getCountByName()

com/cym/service/AdminService.java#getCountByName

```java
	public Long getCountByName(String name) {
		return sqlHelper.findCountByQuery(new ConditionAndWrapper().eq(Admin::getName, name), Admin.class);
	}
```

可以看到进行sql查询，查看数据库是否存在用户。不存在此用户就在service层面创建用户，跟进adminService.addOver。

com/cym/service/AdminService.java#addOver()

```java
	public void addOver(Admin admin, String[] groupIds) {
		sqlHelper.insertOrUpdate(admin);

		sqlHelper.deleteByQuery(new ConditionAndWrapper().eq(AdminGroup::getAdminId, admin.getId()), AdminGroup.class);
		if (admin.getType() == 1 && groupIds != null) {
			for (String id : groupIds) {
				AdminGroup adminGroup = new AdminGroup();
				adminGroup.setAdminId(admin.getId());
				adminGroup.setGroupId(id);
				sqlHelper.insert(adminGroup);
			}
		}
	}
```

这个方法直接将admin添加到数据库，deleteByQuery就是根据admin_id删除admin_group的数据，不重要，dmin.getType() == 1就是非管理员，管理员的type为0，不会走到这里。

以上两个路由都接收的Admin admin，

com/cym/model/Admin.java

```java
public class Admin extends BaseModel {
	String name;
	String pass;
	// 谷歌秘钥
	String key;
	// 是否开启谷歌验证
	@InitValue("false")
	Boolean auth;

	// 是否开启api
	@InitValue("false")
	Boolean api;

	String token;
	// 自动登录key
	String autoKey;
	
	// 类型 0 超管 1 受限用户
	@InitValue("0")
	Integer type;
```

admin类型里面包含了自动登录key，autoKey。

com/cym/controller/adminPage/LoginController.java

```java
@Mapping("autoLogin")
public JsonResult autoLogin(String autoKey) {

   // 用户名密码
   Admin admin = adminService.getByAutoKey(autoKey);
   if (admin != null) {
      // 登录成功
      Context.current().sessionSet("localType", "local");
      Context.current().sessionSet("isLogin", true);
      Context.current().sessionSet("admin", admin);
      Context.current().sessionRemove("imgCode"); // 立刻销毁验证码

      // 检查更新
      versionConfig.checkVersion();

      return renderSuccess(admin);
   } else {
      return renderError();
   }

}
```

这个功能点可以直接登录，什么二次验证都不用管。

com/cym/service/AdminService.java#getByAutoKey

```java
	public Admin getByAutoKey(String autoKey) {
		return sqlHelper.findOneByQuery(new ConditionAndWrapper().eq(Admin::getAutoKey, autoKey), Admin.class);
	}
```

就是从数据库取autokey。

所以以上changePassOver，addOver两个路由，在发送数据包的时候只要autoKey，直接就可以注入到数据库，然后通过autoLogin接口传入autoKey即可通过认证，绕过密码、google认证。

### 复现
![image](https://github.com/cym1102/nginxWebUI/assets/66824584/76124f1d-25bd-4816-9010-f89e6b8e34bc)
成功注入到数据库
![image](https://github.com/cym1102/nginxWebUI/assets/66824584/9102e034-b46c-4514-89fc-44949192316e)
![image](https://github.com/cym1102/nginxWebUI/assets/66824584/3a7b37e7-59a6-418f-9cca-7dfc4feea8e7)
成功注入到数据库
![image](https://github.com/cym1102/nginxWebUI/assets/66824584/dc610dc7-11cf-44c7-b2e6-93916a5c2dc2)
然后调用autoLogin接口，即可获取admin认证。

**Comment by cym1102** [comment]
你们公司安全标准确实高



***@***.***
 
发件人： jason
发送时间： 2023-11-23 15:42
收件人： cym1102/nginxWebUI
抄送： Subscribed
主题： [cym1102/nginxWebUI] Admin 类型可注入autoKey绕过认证 (Issue #116)
com/cym/controller/adminPage/AdminController.java#changePassOver()
	@Mapping("changePassOver")
	public JsonResult changePassOver(Admin admin) {
		adminService.changePassOver(admin);
		return renderSuccess();
	}
	public void changePassOver(Admin admin) {
		if (admin.getAuth()) {
			Admin adminOrg = sqlHelper.findById(admin.getId(), Admin.class);
			if (StrUtil.isEmpty(adminOrg.getKey())) {
				admin.setKey(authUtils.makeKey());
			}
		} else {
			admin.setKey("");
		}
		if (StrUtil.isNotEmpty(admin.getPass())) {
			admin.setPass(EncodePassUtils.encode(admin.getPass()));
		} else {
			admin.setPass(null);
		}
		sqlHelper.updateById(admin);
	}
这里也是对admin.getId()判断，然后来改密码。
com/cym/controller/adminPage/AdminController.java
	@Mapping("addOver")
	public JsonResult addOver(Admin admin, String[] parentId) {
		if (StrUtil.isEmpty(admin.getId())) {
			Long count = adminService.getCountByName(admin.getName());
			if (count > 0) {
				return renderError(m.get("adminStr.nameRepetition"));
			}
		} else {
			Long count = adminService.getCountByNameWithOutId(admin.getName(), admin.getId());
			if (count > 0) {
				return renderError(m.get("adminStr.nameRepetition"));
			}
		}
		adminService.addOver(admin, parentId);
		return renderSuccess();
	}
添加用户的路由, 可以控制admin，parentId，admin.getId()是否为空，不为空进入adminService.getCountByName，跟进getCountByName()
com/cym/service/AdminService.java#getCountByName
	public Long getCountByName(String name) {
		return sqlHelper.findCountByQuery(new ConditionAndWrapper().eq(Admin::getName, name), Admin.class);
	}
可以看到进行sql查询，查看数据库是否存在用户。不存在此用户就在service层面创建用户，跟进adminService.addOver。
com/cym/service/AdminService.java#addOver()
	public void addOver(Admin admin, String[] groupIds) {
		sqlHelper.insertOrUpdate(admin);
		sqlHelper.deleteByQuery(new ConditionAndWrapper().eq(AdminGroup::getAdminId, admin.getId()), AdminGroup.class);
		if (admin.getType() == 1 && groupIds != null) {
			for (String id : groupIds) {
				AdminGroup adminGroup = new AdminGroup();
				adminGroup.setAdminId(admin.getId());
				adminGroup.setGroupId(id);
				sqlHelper.insert(adminGroup);
			}
		}
	}
这个方法直接将admin添加到数据库，deleteByQuery就是根据admin_id删除admin_group的数据，不重要，dmin.getType() == 1就是非管理员，管理员的type为0，不会走到这里。
以上两个路由都接收的Admin admin，
com/cym/model/Admin.java
public class Admin extends BaseModel {
	String name;
	String pass;
	// 谷歌秘钥
	String key;
	// 是否开启谷歌验证
	@InitValue("false")
	Boolean auth;
	// 是否开启api
	@InitValue("false")
	Boolean api;
	String token;
	// 自动登录key
	String autoKey;
	
	// 类型 0 超管 1 受限用户
	@InitValue("0")
	Integer type;
admin类型里面包含了自动登录key，autoKey。
com/cym/controller/adminPage/LoginController.java
@Mapping("autoLogin")
public JsonResult autoLogin(String autoKey) {
   // 用户名密码
   Admin admin = adminService.getByAutoKey(autoKey);
   if (admin != null) {
      // 登录成功
      Context.current().sessionSet("localType", "local");
      Context.current().sessionSet("isLogin", true);
      Context.current().sessionSet("admin", admin);
      Context.current().sessionRemove("imgCode"); // 立刻销毁验证码
      // 检查更新
      versionConfig.checkVersion();
      return renderSuccess(admin);
   } else {
      return renderError();
   }
}
这个功能点可以直接登录，什么二次验证都不用管。
com/cym/service/AdminService.java#getByAutoKey
	public Admin getByAutoKey(String autoKey) {
		return sqlHelper.findOneByQuery(new ConditionAndWrapper().eq(Admin::getAutoKey, autoKey), Admin.class);
	}
就是从数据库取autokey。
所以以上changePassOver，addOver两个路由，在发送数据包的时候只要autoKey，直接就可以注入到数据库，然后通过autoLogin接口传入autoKey即可通过认证，绕过密码、google认证。
复现

成功注入到数据库


成功注入到数据库

然后调用autoLogin接口，即可获取admin认证。

**Comment by cym1102** [comment]
还有没有其他测出来的问题, 我一并改了



***@***.***
 
发件人： jason
发送时间： 2023-11-23 15:42
收件人： cym1102/nginxWebUI
抄送： Subscribed
主题： [cym1102/nginxWebUI] Admin 类型可注入autoKey绕过认证 (Issue #116)
com/cym/controller/adminPage/AdminController.java#changePassOver()
	@Mapping("changePassOver")
	public JsonResult changePassOver(Admin admin) {
		adminService.changePassOver(admin);
		return renderSuccess();
	}
	public void changePassOver(Admin admin) {
		if (admin.getAuth()) {
			Admin adminOrg = sqlHelper.findById(admin.getId(), Admin.class);
			if (StrUtil.isEmpty(adminOrg.getKey())) {
				admin.setKey(authUtils.makeKey());
			}
		} else {
			admin.setKey("");
		}
		if (StrUtil.isNotEmpty(admin.getPass())) {
			admin.setPass(EncodePassUtils.encode(admin.getPass()));
		} else {
			admin.setPass(null);
		}
		sqlHelper.updateById(admin);
	}
这里也是对admin.getId()判断，然后来改密码。
com/cym/controller/adminPage/AdminController.java
	@Mapping("addOver")
	public JsonResult addOver(Admin admin, String[] parentId) {
		if (StrUtil.isEmpty(admin.getId())) {
			Long count = adminService.getCountByName(admin.getName());
			if (count > 0) {
				return renderError(m.get("adminStr.nameRepetition"));
			}
		} else {
			Long count = adminService.getCountByNameWithOutId(admin.getName(), admin.getId());
			if (count > 0) {
				return renderError(m.get("adminStr.nameRepetition"));
			}
		}
		adminService.addOver(admin, parentId);
		return renderSuccess();
	}
添加用户的路由, 可以控制admin，parentId，admin.getId()是否为空，不为空进入adminService.getCountByName，跟进getCountByName()
com/cym/service/AdminService.java#getCountByName
	public Long getCountByName(String name) {
		return sqlHelper.findCountByQuery(new ConditionAndWrapper().eq(Admin::getName, name), Admin.class);
	}
可以看到进行sql查询，查看数据库是否存在用户。不存在此用户就在service层面创建用户，跟进adminService.addOver。
com/cym/service/AdminService.java#addOver()
	public void addOver(Admin admin, String[] groupIds) {
		sqlHelper.insertOrUpdate(admin);
		sqlHelper.deleteByQuery(new ConditionAndWrapper().eq(AdminGroup::getAdminId, admin.getId()), AdminGroup.class);
		if (admin.getType() == 1 && groupIds != null) {
			for (String id : groupIds) {
				AdminGroup adminGroup = new AdminGroup();
				adminGroup.setAdminId(admin.getId());
				adminGroup.setGroupId(id);
				sqlHelper.insert(adminGroup);
			}
		}
	}
这个方法直接将admin添加到数据库，deleteByQuery就是根据admin_id删除admin_group的数据，不重要，dmin.getType() == 1就是非管理员，管理员的type为0，不会走到这里。
以上两个路由都接收的Admin admin，
com/cym/model/Admin.java
public class Admin extends BaseModel {
	String name;
	String pass;
	// 谷歌秘钥
	String key;
	// 是否开启谷歌验证
	@InitValue("false")
	Boolean auth;
	// 是否开启api
	@InitValue("false")
	Boolean api;
	String token;
	// 自动登录key
	String autoKey;
	
	// 类型 0 超管 1 受限用户
	@InitValue("0")
	Integer type;
admin类型里面包含了自动登录key，autoKey。
com/cym/controller/adminPage/LoginController.java
@Mapping("autoLogin")
public JsonResult autoLogin(String autoKey) {
   // 用户名密码
   Admin admin = adminService.getByAutoKey(autoKey);
   if (admin != null) {
      // 登录成功
      Context.current().sessionSet("localType", "local");
      Context.current().sessionSet("isLogin", true);
      Context.current().sessionSet("admin", admin);
      Context.current().sessionRemove("imgCode"); // 立刻销毁验证码
      // 检查更新
      versionConfig.checkVersion();
      return renderSuccess(admin);
   } else {
      return renderError();
   }
}
这个功能点可以直接登录，什么二次验证都不用管。
com/cym/service/AdminService.java#getByAutoKey
	public Admin getByAutoKey(String autoKey) {
		return sqlHelper.findOneByQuery(new ConditionAndWrapper().eq(Admin::getAutoKey, autoKey), Admin.class);
	}
就是从数据库取autokey。
所以以上changePassOver，addOver两个路由，在发送数据包的时候只要autoKey，直接就可以注入到数据库，然后通过autoLogin接口传入autoKey即可通过认证，绕过密码、google认证。
复现

成功注入到数据库


成功注入到数据库

然后调用autoLogin接口，即可获取admin认证。
