### ISSUE TITLE
集群部署

### ISSUE THREAD

**Issue by yejfgit** [cym1102/nginxWebUI#118]
集群部署，替换文件可以同学修改多台机器的文件吗

**Comment by cym1102** [comment]
不会自动同步, 得你去手动操作



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月7日(星期四) 下午4:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cym1102/nginxWebUI] 集群部署 (Issue #118)





 
增加了远程服务器会自动同步吗，还是需要手动触发一下
