### ISSUE TITLE
nginxWebUI runCmd 远程命令执行漏洞

### ISSUE THREAD

**Issue by yurenzhen** [cym1102/nginxWebUI#119]
https://avd.aliyun.com/detail?id=AVD-2023-1672641

严重 nginxWebUI runCmd 远程命令执行漏洞
CVE编号

N/A
利用情况

漏洞武器化
补丁情况

官方补丁
披露时间

2023-05-05
该漏洞已被黑客武器化，用于大规模蠕虫传播、勒索挖矿，建议您立即关注并修复。
漏洞描述
nginxWebUI 是一款 Nginx可视化配置管理工具。2023年国内安全社区披露其存在权限绕过与后台命令执行漏洞，攻击者可在无需登录的情况下绕过路由权限校验，执行任意命令，控制服务器。
解决建议
利用安全组功能设置 nginxWebUI 仅对可信地址开放。

**Comment by cym1102** [comment]
这个漏洞应该已经修复了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月7日(星期四) 晚上8:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [cym1102/nginxWebUI] nginxWebUI runCmd 远程命令执行漏洞 (Issue #119)





 
https://avd.aliyun.com/detail?id=AVD-2023-1672641
 
严重 nginxWebUI runCmd 远程命令执行漏洞
 CVE编号
 
N/A
 利用情况
 
漏洞武器化
 补丁情况
 
官方补丁
 披露时间
 
2023-05-05
 该漏洞已被黑客武器化，用于大规模蠕虫传播、勒索挖矿，建议您立即关注并修复。
 漏洞描述
 nginxWebUI 是一款 Nginx可视化配置管理工具。2023年国内安全社区披露其存在权限绕过与后台命令执行漏洞，攻击者可在无需登录的情况下绕过路由权限校验，执行任意命令，控制服务器。
 解决建议
 利用安全组功能设置 nginxWebUI 仅对可信地址开放。
