### ISSUE TITLE
个人使用几点建议

### ISSUE THREAD

**Issue by wangxm345566462** [cym1102/nginxWebUI#12]
首先感谢git主的代码贡献。

个人这两天使用有几点用起来特别不舒服的。
以下仅代表个人观点。
1 . 建议，增加多行批量添加，可以以分号切分，切换表单模式或文本模式。 文本可以自动解析成表单。
2.  建议,  重启nginx ，弹窗可以通过 回车关闭。
3.  建议，菜单歧义，生成conf ，不如叫坐 nginx 管理。
4.  建议，上传静态网页 与 反向代理的功能有关联关系，第一次使用不知道如何去配置静态页，反向代理菜单有些不易理解。
5.  错误，远程服务器-》切换到此服务器 -》 后， 上传证书出现错误。
6.  建议，摸板可以根据已配置的项反向生成摸板。比如现在已经配置好几条了，我想把一些共性配置生成摸板。
7.  建议，提供配置文件配置更新url，由于军用内网环境使用，没有互联网。

**Comment by cym1102** [comment]
感谢建议



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月22日(周四) 下午3:30
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cym1102/nginxWebUI] 个人使用几点建议 (#12)




 
首先感谢git主的代码贡献。
 
个人这两天使用有几点用起来特别不舒服的。
 以下仅代表个人观点。
 1 . 建议，增加多行批量添加，可以以分号切分，切换表单模式或文本模式。 文本可以自动解析成表单。
 2.  建议,  重启nginx ，弹窗可以通过 回车关闭。
 3.  建议，菜单歧义，生成conf ，不如叫坐 nginx 管理。
 4.  建议，上传静态网页 与 反向代理的功能有关联关系，第一次使用不知道如何去配置静态页，反向代理菜单有些不易理解。
 5.  错误，远程服务器-》切换到此服务器 -》 后， 上传证书出现错误。
 6.  建议，摸板可以根据已配置的项反向生成摸板。比如现在已经配置好几条了，我想把一些共性配置生成摸板。

**Comment by cym1102** [comment]
只有5能改, 其他都不好改, 3这个会改变用户习惯

**Comment by wangxm345566462** [comment]
> 只有5能改, 其他都不好改, 3这个会改变用户习惯

嗯。 我只是个人建议。

**Comment by wangxm345566462** [comment]
我觉得 1 2 比较重要。  很多时候是复制过来的一些配置。  2. 鼠标去找 关闭按钮 是很麻烦的。
