### ISSUE TITLE
非常好用的工具

### ISSUE THREAD

**Issue by allonmymind** [cym1102/nginxWebUI#122]
非常好用的工具，能否增加动态域名解析功能，例如ddnsgo的功能，这样的话不用部署多个

**Comment by cym1102** [comment]
nginx做不到的我也做不到



***@***.***
 
发件人： allonmymind
发送时间： 2024-01-16 13:53
收件人： cym1102/nginxWebUI
抄送： Subscribed
主题： [cym1102/nginxWebUI] 非常好用的工具 (Issue #122)
非常好用的工具，能否增加动态域名解析功能，例如ddnsgo的功能，这样的话不用部署多个
