### ISSUE TITLE
window10 docker desktop 部署无法访问

### ISSUE THREAD

**Issue by xinxinQ** [cym1102/nginxWebUI#126]
window版本的docker部署和容器显示运行正常，浏览器访问错误，log如下：
INFO  2024-02-23 15:25:09.517 [-main][*][o.noear.solon.Solon]: 
App: Start loading
INFO  2024-02-23 15:25:09.524 [-Solon-executor-1][*][o.noear.solon.Solon]: 
Logging: console {level=TRACE, enable=true}
INFO  2024-02-23 15:25:09.552 [-main][*][o.noear.solon.Solon]: 
App: Plugin starting
INFO  2024-02-23 15:25:09.622 [-main][*][o.noear.solon.Solon]: 
View: load: FreemarkerRender
INFO  2024-02-23 15:25:09.624 [-main][*][o.noear.solon.Solon]: 
View: load: org.noear.solon.view.freemarker.FreemarkerRender
INFO  2024-02-23 15:25:09.624 [-main][*][o.noear.solon.Solon]: 
Render mapping: .ftl=FreemarkerRender
INFO  2024-02-23 15:25:09.644 [-main][*][o.noear.solon.Solon]: 
Session: Local session state plugin is loaded
INFO  2024-02-23 15:25:09.647 [-main][*][o.noear.solon.Solon]: 
App: Bean scanning
INFO  2024-02-23 15:25:09.794 [-main][*][o.noear.solon.Solon]: 
Render mapping: .html=FreemarkerRender
INFO  2024-02-23 15:25:09.795 [-main][*][o.noear.solon.Solon]: 
Render mapping: @json=StringSerializerRender#SnackSerializer
INFO  2024-02-23 15:25:09.796 [-main][*][o.noear.solon.Solon]: 
Render mapping: @type_json=StringSerializerRender#SnackSerializer
INFO  2024-02-23 15:25:12.726 [-main][*][c.c.c.InitConfig]: 
nginxIsRun:false
INFO  2024-02-23 15:25:12.733 [-main][*][c.c.c.InitConfig]: 
runCmd:nginx -c /home/nginxWebUI/nginx.conf
INFO  2024-02-23 15:25:12.744 [-main][*][c.c.c.InitConfig]: 
                  _              _       __       __     __  __ ____
   ____   ____ _ (_)____   _  __| |     / /___   / /_   / / / //  _/
  / __ \ / __ `// // __ \ | |/_/| | /| / // _ \ / __ \ / / / / / /  
 / / / // /_/ // // / / /_>  <  | |/ |/ //  __// /_/ // /_/ /_/ /   
/_/ /_/ \__, //_//_/ /_//_/|_|  |__/|__/ \___//_.___/ \____//___/   
       /____/                                                       
       
nginxWebUI 3.8.5

INFO  2024-02-23 15:25:12.941 [-main][*][o.noear.solon.Solon]: 
Connector:main: undertow: Started ServerConnector@{HTTP/1.1,[http/1.1]}{http://localhost:8080}
INFO  2024-02-23 15:25:12.942 [-main][*][o.noear.solon.Solon]: 
Server:main: undertow: Started (undertow 2.2.24/2.4.5) @196ms
INFO  2024-02-23 15:25:12.944 [-main][*][o.noear.solon.Solon]: 
App: End loading elapsed=3622ms pid=7 v=2.4.5

**Comment by cym1102** [comment]
程序启动是正常得, windows下--net=host这个参数是无效的, 你得自己用-p 80:80来映射你需要的端口



***@***.***
 
发件人： stone
发送时间： 2024-02-23 15:28
收件人： cym1102/nginxWebUI
抄送： Subscribed
主题： [cym1102/nginxWebUI] window10 docker desktop 部署无法访问 (Issue #126)
window版本的docker部署和容器显示运行正常，浏览器访问错误，log如下：
INFO 2024-02-23 15:25:09.517 [-main][][o.noear.solon.Solon]:
App: Start loading
INFO 2024-02-23 15:25:09.524 [-Solon-executor-1][][o.noear.solon.Solon]:
Logging: console {level=TRACE, enable=true}
INFO 2024-02-23 15:25:09.552 [-main][][o.noear.solon.Solon]:
App: Plugin starting
INFO 2024-02-23 15:25:09.622 [-main][][o.noear.solon.Solon]:
View: load: FreemarkerRender
INFO 2024-02-23 15:25:09.624 [-main][][o.noear.solon.Solon]:
View: load: org.noear.solon.view.freemarker.FreemarkerRender
INFO 2024-02-23 15:25:09.624 [-main][][o.noear.solon.Solon]:
Render mapping: .ftl=FreemarkerRender
INFO 2024-02-23 15:25:09.644 [-main][][o.noear.solon.Solon]:
Session: Local session state plugin is loaded
INFO 2024-02-23 15:25:09.647 [-main][][o.noear.solon.Solon]:
App: Bean scanning
INFO 2024-02-23 15:25:09.794 [-main][][o.noear.solon.Solon]:
Render mapping: .html=FreemarkerRender
INFO 2024-02-23 15:25:09.795 [-main][][o.noear.solon.Solon]:
Render mapping: @JSON=StringSerializerRender#SnackSerializer
INFO 2024-02-23 15:25:09.796 [-main][][o.noear.solon.Solon]:
Render mapping: @type_json=StringSerializerRender#SnackSerializer
INFO 2024-02-23 15:25:12.726 [-main][][c.c.c.InitConfig]:
nginxIsRun:false
INFO 2024-02-23 15:25:12.733 [-main][][c.c.c.InitConfig]:
runCmd:nginx -c /home/nginxWebUI/nginx.conf
INFO 2024-02-23 15:25:12.744 [-main][][c.c.c.InitConfig]:
_ _ __ __ __ __ ____
____ ____ _ ()___ _ | | / /_ / /_ / / / // /
/ __ \ / __ `// // __ \ | |//| | /| / // _ \ / __ \ / / / / / /
/ / / // // // // / / /> < | |/ |/ // // // // // // /
// // _, ///// ////|_| |/|/ _//./ _///
/__/
nginxWebUI 3.8.5
INFO 2024-02-23 15:25:12.941 [-main][][o.noear.solon.Solon]:
Connector:main: undertow: Started ServerConnector@{HTTP/1.1,[http/1.1]}{http://localhost:8080}
INFO 2024-02-23 15:25:12.942 [-main][][o.noear.solon.Solon]:
Server:main: undertow: Started (undertow 2.2.24/2.4.5) @196ms
INFO 2024-02-23 15:25:12.944 [-main][*][o.noear.solon.Solon]:
App: End loading elapsed=3622ms pid=7 v=2.4.5
