### ISSUE TITLE
docker使用建议

### ISSUE THREAD

**Issue by casselluu** [cym1102/nginxWebUI#129]
--privileged给予的权限太多，如果只是acme生成的文件需要修改权限，可以使用--cap-add=CAP_CHOWN。

**Comment by cym1102** [comment]
好的，我试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月28日(周三) 下午5:35
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cym1102/nginxWebUI] docker使用建议 (Issue #129)




 
--privileged给予的权限太多，如果只是acme生成的文件需要修改权限，可以使用--cap-add=CAP_CHOWN。
