### ISSUE TITLE
后台修改nginx配置文件

### ISSUE THREAD

**Issue by zhangshdn** [cym1102/nginxWebUI#130]
非常感谢贡献出nginxweb
有个问题，我想通过后台接口，修改nginx的配置文件，并且重启，例如，我想增加一个upstream，传入参数，然后修改nginx.conf，重启nginx，有没有现成的功能

**Comment by cym1102** [comment]
有接口，你看看官网说明



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月3日(周日) 下午4:09
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cym1102/nginxWebUI] 后台修改nginx配置文件 (Issue #130)




 
非常感谢贡献出nginxweb
 有个问题，我想通过后台接口，修改nginx的配置文件，并且重启，例如，我想增加一个upstream，传入参数，然后修改nginx.conf，重启nginx，有没有现成的功能
