### ISSUE TITLE
通过dns记录新申请的证书pem和key的位置反了

### ISSUE THREAD

**Issue by OuroborosCaster** [cym1102/nginxWebUI#131]
<img width="800" alt="无标题" src="https://github.com/cym1102/nginxWebUI/assets/49244214/cd415985-957e-4bfe-83e8-2ca3b7a361ee">

而且不知道啥时候证书位置跑到/root/.acme.sh下面去了，以前都只在/home/nginxWebUI/.acme.sh，试了在BOOT_OPTIONS指定--server.port=8080 --project.home=/home/nginxWebUI/ 也不管用

使用的是docker部署，部署在Debian10、11和Centos 8.5上

**Comment by moyilong** [comment]
src/main/java/com/cym/controller/adminPage/CertController.java
![image](https://github.com/cym1102/nginxWebUI/assets/3390944/8c329854-fdfc-4e58-bdbb-54f4272e64dc)
这俩函数写反了吧

**Comment by cym1102** [comment]
你说得对, 我马上改过来

**Comment by cym1102** [comment]
3.8.8已修复这个bug

**Comment by cym1102** [comment]
> <img alt="无标题" width="800" src="https://private-user-images.githubusercontent.com/49244214/309546615-cd415985-957e-4bfe-83e8-2ca3b7a361ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MTk1OTEsIm5iZiI6MTcwOTUxOTI5MSwicGF0aCI6Ii80OTI0NDIxNC8zMDk1NDY2MTUtY2Q0MTU5ODUtOTU3ZS00YmZlLTgzZTgtMmNhM2I3YTM2MWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDAyMjgxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0NzUzZThjMjU1NWY4NzBkYTVkMTY5MDFlNGU1OTFhMDQwMzIxNThhMmEzM2MyMmQ4MzkyYmE3MmQzMmQ1YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AJ3x7ztUX0pNQ_Clhovdag39Cw7hyjCjQl9cluW3_rI">
> 而且不知道啥时候证书位置跑到/root/.acme.sh下面去了，以前都只在/home/nginxWebUI/.acme.sh，试了在BOOT_OPTIONS指定--server.port=8080 --project.home=/home/nginxWebUI/ 也不管用
> 
> 使用的是docker部署，部署在Debian10、11和Centos 8.5上

现在使用acme的默认部署方式, acme默认部署申请的证书就在/root/下, 所以证书也只能指向/root/, 这样部署的好处是无需魔改acme的代码, acme的兼容性更高, 以前无法申请华为dns的证书, 现在这样部署就可以申请了

**Comment by moyilong** [comment]
其实可以通过设置HOME环境变量的方式修改到PROJECT_HOME

**Comment by cym1102** [comment]
> 其实可以通过设置HOME环境变量的方式修改到PROJECT_HOME

是吗? 我试一试

**Comment by cym1102** [comment]
3.8.9 改好了, 还是使用应用程序目录
