### ISSUE TITLE
证书的首次申请用的是续签的命令

### ISSUE THREAD

**Issue by OuroborosCaster** [cym1102/nginxWebUI#132]
申请新证书时，提示如下
<img width="800" alt="无标题" src="https://github.com/cym1102/nginxWebUI/assets/49244214/acda78dc-812f-444d-8430-dbff39c96ad0">
续签没有问题

**Comment by cym1102** [comment]
用的3.9.0吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月6日(周三) 晚上6:06
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cym1102/nginxWebUI] 证书的首次申请用的是续签的命令 (Issue #132)




 
申请新证书时，提示如下
 default.png (view on web)
 续签没有问题

**Comment by cym1102** [comment]
命令没有问题啊, 你重新获取一下txt记录再执行, 或者新建一条记录再试一下, 我之前改了acme.sh路径, 然后又改回来了, 导致有些版本路径不对, 你试一下

**Comment by OuroborosCaster** [comment]
> 命令没有问题啊, 你重新获取一下txt记录再执行, 或者新建一条记录再试一下, 我之前改了acme.sh路径, 然后又改回来了, 导致有些版本路径不对, 你试一下

我重新测试过了，很奇怪，第一次申请必然不会成功，无论是否重新获取DNS记录都一样
但如果把容器重启一下，再申请，就成功了
3.9.0和最新的3.9.1都在debian11和centos8服务器分别测试过，都是这样，无论申请的是ecc还是rsa

**Comment by cym1102** [comment]
使用txt进行证书申请就会有更多问题，最好还是使用api_key进行获取



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月7日(周四) 下午2:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cym1102/nginxWebUI] 证书的首次申请用的是续签的命令 (Issue #132)




  
命令没有问题啊, 你重新获取一下txt记录再执行, 或者新建一条记录再试一下, 我之前改了acme.sh路径, 然后又改回来了, 导致有些版本路径不对, 你试一下
  
我重新测试过了，很奇怪，第一次申请必然不会成功，无论是否重新获取DNS记录都一样
 但如果把容器重启一下，再申请，就成功了
 3.9.0和最新的3.9.1都在debian11和centos8服务器分别测试过，都是这样，无论申请的是ecc还是rsa

**Comment by wangxm345566462** [comment]
遇到同样的问题。
![image](https://github.com/cym1102/nginxWebUI/assets/17328090/7e788c35-eebc-49b6-8321-e4b880e27a3b)
![image](https://github.com/cym1102/nginxWebUI/assets/17328090/d04dd883-4f55-4801-8cba-ac7082275d88)

**Comment by lileyzhao** [comment]
怎么解决啊，一直申请不了证书

**Comment by cym1102** [comment]
不要慌，我正在解决这个问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月18日(周四) 中午1:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cym1102/nginxWebUI] 证书的首次申请用的是续签的命令 (Issue #132)




 
怎么解决啊，一直申请不了证书
