### ISSUE TITLE
登录时验证码无法显示

### ISSUE THREAD

**Issue by jerryzhang721** [cym1102/nginxWebUI#135]
我在群晖系统中安装了nginxWebUI希望用于管理群晖自带的nginx，安装完成后出现登录时验证码无法显示的问题

**Comment by cym1102** [comment]
系统缺少字库, ubuntu上是apt install fontconfig, 我不知道群晖是咋样



***@***.***
 
发件人： jerryzhang721
发送时间： 2024-03-26 16:55
收件人： cym1102/nginxWebUI
抄送： Subscribed
主题： [cym1102/nginxWebUI] 登录时验证码无法显示 (Issue #135)
我在群晖系统中安装了nginxWebUI希望用于管理群晖自带的nginx，安装完成后出现登录时验证码无法显示的问题
