### ISSUE TITLE
html 里引用资源文件的链接在使用非标准端口时有问题

### ISSUE THREAD

**Issue by ZhReimu** [cym1102/nginxWebUI#139]
如图，使用非标准端口时首页的 html 没问题，但是其中引用的资源文件全挂了，因为没带上端口
NginxWebUI 版本: 3.9.7
启动命令: `java -jar nginxWebUI.jar --server.port=8007 --server.address=127.0.0.1 --logging.level.oshi.util.Util=debug --project.home=%PROJECT_HOME%`
nginx 反代配置
```conf
    # nginx web ui
    server {
        listen       12345;
        server_name  example.top;
        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 90;
            proxy_pass http://127.0.0.1:8007;
        }
        
        ssl_certificate  certs/example.top.crt;
        ssl_certificate_key certs/example.top.key;
    }
```
![image](https://github.com/cym1102/nginxWebUI/assets/58155247/73559381-8117-4376-9662-433014f7d52f)

**Comment by cym1102** [comment]
这个, 你代理的时候加了Host参数吗? 加了的话应该会带端口的.



***@***.***
 
发件人： Mr.X
发送时间： 2024-04-01 17:26
收件人： cym1102/nginxWebUI
抄送： Subscribed
主题： [cym1102/nginxWebUI] html 里引用资源文件的链接在使用非标准端口时有问题 (Issue #139)
如图，使用非标准端口时首页的 html 没问题，但是其中引用的资源文件全挂了，因为没带上端口
image.png (view on web)

**Comment by ZhReimu** [comment]
> 这个, 你代理的时候加了Host参数吗? 加了的话应该会带端口的. ***@***.*** 发件人： Mr.X 发送时间： 2024-04-01 17:26 收件人： cym1102/nginxWebUI 抄送： Subscribed 主题： [cym1102/nginxWebUI] html 里引用资源文件的链接在使用非标准端口时有问题 (Issue #139) 如图，使用非标准端口时首页的 html 没问题，但是其中引用的资源文件全挂了，因为没带上端口 image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
明白了, 我的问题, nginx 转发时把 port 去掉了, 反代后边的服务器就拿不到这个参数了, 改正后就可以了
```conf
    server {
        listen 8099;
        server_name test.127.0.0.1.nip.io;
        
        location / {
            proxy_set_header Host $host:$server_port;
            proxy_pass http://localhost:8080;
        }
    }
```
