### ISSUE TITLE
提个可有可无的建议

### ISSUE THREAD

**Issue by klxyy** [cym1102/nginxWebUI#141]
首页上的磁盘使用可以只显示根目录么，显示那么多同样的内容也没什么用啊

**Comment by cym1102** [comment]
这个获取磁盘的api的还要照顾Windows，所以把所有挂载的磁盘都拿了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月8日(周一) 中午1:15
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cym1102/nginxWebUI] 提个可有可无的建议 (Issue #141)




 
首页上的磁盘使用可以只显示根目录么，显示那么多同样的内容也没什么用啊
