### ISSUE TITLE
请问反向代理设置 监控路径 怎么设置？

### ISSUE THREAD

**Issue by SunHHB** [cym1102/nginxWebUI#142]
监控路径 默认是/ 其他后面，我想使用不同路径到不同的地址，添加路径比如 ：/alist  都无效，请问是这样设置吗？

**Comment by cym1102** [comment]
这里一两句话不太好沟通, 你进群聊聊吧



***@***.***
 
发件人： sunhhb
发送时间： 2024-04-11 10:11
收件人： cym1102/nginxWebUI
抄送： Subscribed
主题： [cym1102/nginxWebUI] 请问反向代理设置 监控路径 怎么设置？ (Issue #142)
监控路径 默认是/ 其他后面，我想使用不同路径到不同的地址，添加路径比如 ：/alist 都无效，请问是这样设置吗？
