### ISSUE TITLE
意外断电数据库文件容易损坏

### ISSUE THREAD

**Issue by zelong77** [cym1102/nginxWebUI#144]
这个有办法优化吗?是不是和数据库的synchronous模式有关.

**Comment by cym1102** [comment]
这个问题, 也有一些用户反馈, h2数据库容易被损坏, 恐怕需要将来有一天切换到sqlite上才能解决, 不过h2官方提供了修复h2数据库的方案, 你可以搜索一下



***@***.***
 
发件人： zelong77
发送时间： 2024-04-23 14:35
收件人： cym1102/nginxWebUI
抄送： Subscribed
主题： [cym1102/nginxWebUI] 意外断电数据库文件容易损坏 (Issue #144)
这个有办法优化吗?是不是和数据库的synchronous模式有关.

**Comment by zelong77** [comment]
> 这个问题, 也有一些用户反馈, h2数据库容易被损坏, 恐怕需要将来有一天切换到sqlite上才能解决, 不过h2官方提供了修复h2数据库的方案, 你可以搜索一下 ***@***.*** 发件人： zelong77 发送时间： 2024-04-23 14:35 收件人： cym1102/nginxWebUI 抄送： Subscribed 主题： [cym1102/nginxWebUI] 意外断电数据库文件容易损坏 (Issue #144) 这个有办法优化吗?是不是和数据库的synchronous模式有关. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

好的,谢谢,我每天也都有备份就是了.

**Comment by zelong77** [comment]
好的  我试试
