### ISSUE TITLE
nginx: [emerg] unknown directive "http2" in /home/nginxWebUI/temp/nginx.conf:14

### ISSUE THREAD

**Issue by Lizhen0628** [cym1102/nginxWebUI#146]
nginx: [emerg] unknown directive "http2" in /home/nginxWebUI/temp/nginx.conf:14

**Comment by cym1102** [comment]
你的nginx版本在1.24以下，选择旧版http2写法



---Original---
From: ***@***.***&gt;
Date: Wed, May 15, 2024 15:17 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [cym1102/nginxWebUI] nginx: [emerg] unknown directive "http2" in/home/nginxWebUI/temp/nginx.conf:14 (Issue #146)




 
nginx: [emerg] unknown directive "http2" in /home/nginxWebUI/temp/nginx.conf:14
