### ISSUE TITLE
建议升级docker镜像中的nginx版本

### ISSUE THREAD

**Issue by wangr0031** [cym1102/nginxWebUI#147]
最新docker镜像： cym1102/nginxwebui:4.1.0
在配置nginx的反向路由的时候，启用http2版本 nginx >=1.25的写法，且默认为这个配置
![image](https://github.com/cym1102/nginxWebUI/assets/24863189/b9ce06e7-ab24-4f98-a98f-eb8911d1fba7)
nginxwebui中内置的nginx版本为1.24版本，并不支持，建议升级下内置的nginx版本
![image](https://github.com/cym1102/nginxWebUI/assets/24863189/3e1f0bca-af8e-4235-aa78-c2cd34ceda76)
或者 将默认的http2版本为 nginx < 1.25

**Comment by cym1102** [comment]
暂时升级不了, 先把默认选项改过来把
