### ISSUE TITLE
升级 4.1.3 后两步验证一直提示失败，无法关闭

### ISSUE THREAD

**Issue by shis95** [cym1102/nginxWebUI#148]
1. 4.1.3 通过 java -jar /home/nginxWebUI.jar --project.findPass=true 无法关闭；
2. 降级至4.1.0后还是提示验证失败，通过 java -jar /home/nginxWebUI.jar --project.findPass=true 无法关闭，容器直接停止了；

**Comment by cym1102** [comment]
这个参数是找回密码用的, 不是关闭程序用的, 要关闭程序, 直接运行pkill java就行了



***@***.***
 
发件人： shis
发送时间： 2024-05-30 11:47
收件人： cym1102/nginxWebUI
抄送： Subscribed
主题： [cym1102/nginxWebUI] 升级 4.1.3 后两步验证一直提示失败，无法关闭 (Issue #148)
4.1.3 通过 java -jar /home/nginxWebUI.jar --project.findPass=true 无法关闭；
降级至4.1.0后还是提示验证失败，通过 java -jar /home/nginxWebUI.jar --project.findPass=true 无法关闭，容器直接停止了；

**Comment by shis95** [comment]
不是关闭程序，是关闭两步验证，在4.1.0执行，直接就关闭程序了，4.1.3上执行一直卡住不动

**Comment by shis95** [comment]
![image](https://github.com/cym1102/nginxWebUI/assets/34735016/af8b0069-ef36-4524-9afb-9f075c9f4e46)
4.1.0执行效果

**Comment by shis95** [comment]
![image](https://github.com/cym1102/nginxWebUI/assets/34735016/c271fa92-abe1-4d13-8262-9d2d5d44eb59)
4.1.3执行效果

**Comment by cym1102** [comment]
等我验证一下



***@***.***
 
发件人： shis
发送时间： 2024-05-30 13:35
收件人： cym1102/nginxWebUI
抄送： cym1102; Comment
主题： Re: [cym1102/nginxWebUI] 升级 4.1.3 后两步验证一直提示失败，无法关闭 (Issue #148)
image.png (view on web)
4.1.3执行效果

**Comment by cym1102** [comment]
我测试过, 没有问题
