### ISSUE TITLE
docker 启动报错nohup: redirecting stderr to stdout

### ISSUE THREAD

**Issue by JansenChang** [cym1102/nginxWebUI#15]
nohup: redirecting stderr to stdout

**Comment by cym1102** [comment]
这不是报错， 这是nohup命令的正常输出




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cym1102/nginxWebUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月24日(星期四) 下午2:39
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[cym1102/nginxWebUI] docker 启动报错nohup: redirecting stderr to stdout (#15)





 
nohup: redirecting stderr to stdout
