### ISSUE TITLE
反向代理优化建议

### ISSUE THREAD

**Issue by sleikang** [cym1102/nginxWebUI#150]
希望能像Lucky批量配置方便，就是同一个端口绑定不同的二级域名，lucky配置方便但是限制了很多原生配置功能
还有一个就是增加和修改配置能自动重启生效而不是每次需要停止再重启，如果本身反代自己本身，我添加一个反代需要先停止，那么管理页面本身就不能访问了
![image](https://github.com/cym1102/nginxWebUI/assets/23020770/3c9293d7-933a-4ece-b64d-105cc5cb8220)

**Comment by cym1102** [comment]
这些功能现在都是有的



---原始邮件---
发件人: "xiaojun ***@***.***&gt;
发送时间: 2024年6月10日(周一) 晚上6:03
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cym1102/nginxWebUI] 反向代理优化建议 (Issue #150)




 
希望能像Lucky批量配置方便，就是同一个端口绑定不同的二级域名，lucky配置方便但是限制了很多原生配置功能
 还有一个就是增加和修改配置能自动重启生效而不是每次需要停止再重启，如果本身反代自己本身，我添加一个反代需要先停止，那么管理页面本身就不能访问了
 image.png (view on web)

**Comment by cym1102** [comment]
你要不停机重启，直接使用重新装载就行



---原始邮件---
发件人: "xiaojun ***@***.***&gt;
发送时间: 2024年6月10日(周一) 晚上6:03
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cym1102/nginxWebUI] 反向代理优化建议 (Issue #150)




 
希望能像Lucky批量配置方便，就是同一个端口绑定不同的二级域名，lucky配置方便但是限制了很多原生配置功能
 还有一个就是增加和修改配置能自动重启生效而不是每次需要停止再重启，如果本身反代自己本身，我添加一个反代需要先停止，那么管理页面本身就不能访问了
 image.png (view on web)

**Comment by sleikang** [comment]
> 这些功能现在都是有的
> […](#)
> ---原始邮件--- 发件人: "xiaojun ***@***.***&gt; 发送时间: 2024年6月10日(周一) 晚上6:03 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [cym1102/nginxWebUI] 反向代理优化建议 (Issue #150) 希望能像Lucky批量配置方便，就是同一个端口绑定不同的二级域名，lucky配置方便但是限制了很多原生配置功能 还有一个就是增加和修改配置能自动重启生效而不是每次需要停止再重启，如果本身反代自己本身，我添加一个反代需要先停止，那么管理页面本身就不能访问了 image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;
我知道这个可以实现 但是这边配置是分离的 就是你这个每个配置都是独立的都有端口号没法一个父级只绑定端口伐证书，子配置绑定域名和反代，他那个是在同一个端口号下面配置子代理，如果想换端口号你这边就得全部一个个修改，他那个只需要修改父级端口号
还有就是当我配置的反代过多后那个配置文件加载框滑动非常卡
![image](https://github.com/cym1102/nginxWebUI/assets/23020770/b5ff95f9-af89-46e5-9eb8-ef3dd7d50b4e)

**Comment by sleikang** [comment]
> 你要不停机重启，直接使用重新装载就行
> […](#)
> ---原始邮件--- 发件人: "xiaojun ***@***.***&gt; 发送时间: 2024年6月10日(周一) 晚上6:03 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [cym1102/nginxWebUI] 反向代理优化建议 (Issue #150) 希望能像Lucky批量配置方便，就是同一个端口绑定不同的二级域名，lucky配置方便但是限制了很多原生配置功能 还有一个就是增加和修改配置能自动重启生效而不是每次需要停止再重启，如果本身反代自己本身，我添加一个反代需要先停止，那么管理页面本身就不能访问了 image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

嗯这个看到了 如果能配置修改完成自己重载就更好了

**Comment by sleikang** [comment]
发现一个新的BUG 就是停留在反代页面一段时间后再点编辑会报错
![image](https://github.com/cym1102/nginxWebUI/assets/23020770/04209422-d352-44e2-ac76-5b018e3c4ddb)

**Comment by cym1102** [comment]
你这是session超时了

**Comment by cym1102** [comment]
你觉得卡点一下分隔文件试试

**Comment by sleikang** [comment]
> 你觉得卡点一下分隔文件试试

按域名分解文件 这个是吧 分割有BUG 就是 目标配置文件不会分割 那个对话框也很卡，目标配置文件分割后编辑框里面是还是全文，虽然下面有域名 展开后是空白的

**Comment by cym1102** [comment]
你这些问题咋那么奇怪, 其他用户都没有遇到这些问题, 要不你到qq群里聊一下你的问题

**Comment by sleikang** [comment]
> 你这是session超时了

正常每次请求如果连接端口都是会建立新的连接建立把，虽然HTTP有会话保持，但是一般都是短链接吧，就算会话超时了应该是再次请求的时候会自动尝试重新建立连接，我F12看每次超时后点多少次编辑都是报错，网络请求里面只有一条登录的http，

**Comment by sleikang** [comment]
> 你这些问题咋那么奇怪, 其他用户都没有遇到这些问题, 要不你到qq群里聊一下你的问题

可能是本身是程序员 对这些操作关注的多 /捂脸

**Comment by cym1102** [comment]
可能是你环境有问题

**Comment by sleikang** [comment]
> 可能是你环境有问题

BUG都是这样 有时候自己电脑怎么复现不了 测试的电脑和客户的电脑就能复现，我调试发现就是ck失效了造成的，但是后端返回的set-cookie都是同一个，所以无论点击多少次都是报错
![image](https://github.com/cym1102/nginxWebUI/assets/23020770/4e870ed4-50b8-4339-a8c5-82fd9fdff337)
![image](https://github.com/cym1102/nginxWebUI/assets/23020770/f4df96c3-b452-4622-a4e9-25741dee0604)
![image](https://github.com/cym1102/nginxWebUI/assets/23020770/b666d01e-5353-453f-b228-c71793c9fbbd)
