### ISSUE TITLE
SMTP 邮件配置发送失败

### ISSUE THREAD

**Issue by Axinyp** [cym1102/nginxWebUI#151]
![image](https://github.com/cym1102/nginxWebUI/assets/42953066/5f9af85a-afaf-473c-a5a5-33a553b4701b)
![image](https://github.com/cym1102/nginxWebUI/assets/42953066/f57e8bc2-6057-47e0-a96a-d0eabcb02fb2)

**Comment by cym1102** [comment]
这是你邮箱配置有误



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月14日(周五) 上午8:51
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cym1102/nginxWebUI] SMTP 邮件配置发送失败 (Issue #151)




 
image.png (view on web)
 image.png (view on web)

**Comment by Axinyp** [comment]
哪里出问题了？，不是这样配置吗？

**Comment by cym1102** [comment]
提示连不上邮箱域名



***@***.***
 
发件人： liufuxin
发送时间： 2024-06-14 13:57
收件人： cym1102/nginxWebUI
抄送： cym1102; State change
主题： Re: [cym1102/nginxWebUI] SMTP 邮件配置发送失败 (Issue #151)
哪里出问题了？，不是这样配置吗？

**Comment by Axinyp** [comment]
我另外一个服务也是用的这个邮箱是正常发送的

**Comment by cym1102** [comment]
检查一下服务器是不是关闭了外网



***@***.***
 
发件人： liufuxin
发送时间： 2024-06-14 14:05
收件人： cym1102/nginxWebUI
抄送： cym1102; State change
主题： Re: [cym1102/nginxWebUI] SMTP 邮件配置发送失败 (Issue #151)
我另外一个服务也是用的这个邮箱是正常发送的

**Comment by Axinyp** [comment]
没有关闭，我另外一个服务也是用的这个邮箱，并且是在同一台机器上运行的

**Comment by cym1102** [comment]
那就是pop3协议和stmp协议搞混了



***@***.***
 
发件人： liufuxin
发送时间： 2024-06-14 14:19
收件人： cym1102/nginxWebUI
抄送： cym1102; State change
主题： Re: [cym1102/nginxWebUI] SMTP 邮件配置发送失败 (Issue #151)
没有关闭，我另外一个服务也是用的这个邮箱，并且是在同一台机器上运行的

**Comment by Lizhen0628** [comment]
> 那就是pop3协议和stmp协议搞混了 ***@***.*** 发件人： liufuxin 发送时间： 2024-06-14 14:19 收件人： cym1102/nginxWebUI 抄送： cym1102; State change 主题： Re: [cym1102/nginxWebUI] SMTP 邮件配置发送失败 (Issue #151) 没有关闭，我另外一个服务也是用的这个邮箱，并且是在同一台机器上运行的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***>

@Axinyp 请问问题解决了吗？我也遇到了这个问题

**Comment by Mapzle** [comment]
> > 那就是pop3协议和stmp协议搞混了 _**@**_.*** 发件人： liufuxin 发送时间： 2024-06-14 14:19 收件人： cym1102/nginxWebUI 抄送： cym1102; State change 主题： Re: [cym1102/nginxWebUI] SMTP 邮件配置发送失败 (Issue [#151](https://github.com/cym1102/nginxWebUI/issues/151)) 没有关闭，我另外一个服务也是用的这个邮箱，并且是在同一台机器上运行的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: _**@**_.***>
> 
> [@Axinyp](https://github.com/Axinyp) 请问问题解决了吗？我也遇到了这个问题

你可以试一下调整java.security中的jdk.tls.disabledAlgorithms，我这里发现在进行ClientHello时使用的是 TLSv1，把TLSv1和TLSv1.1解禁后能正常发送。

**Comment by 7161457** [comment]
今天我测试了,smtp.163的邮箱还是这个问题,请问作者没有帮忙修复吗?

**Comment by 7161457** [comment]
> 今天我测试了,smtp.163的邮箱还是这个问题,请问作者没有帮忙修复吗?

把465端口改为25端口,然后ssl状态,关闭,可以成功发送了
