### ISSUE TITLE
nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead

### ISSUE THREAD

**Issue by 0x11901** [cym1102/nginxWebUI#152]
nginx 1.25.1 换了配置的语法。

> This will not break anything immediately, but just as a heads-up the old format is

```
server {
    listen      90.91.45.3:443 ssl http2;
```
> and the new format for nginx >= 1.25.1 is
```
server {
    listen      90.91.45.3:443 ssl;
    http2  on;
 ```

希望更新一下生成的配置文件。

**Comment by cym1102** [comment]
升级最新版，两种写法都可以配置



---Original---
From: ***@***.***&gt;
Date: Fri, Jun 14, 2024 21:57 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [cym1102/nginxWebUI] nginx: [warn] the "listen ... http2" directiveis deprecated, use the "http2" directive instead (Issue #152)




 
nginx 1.25.1 换了配置的语法。
  
This will not break anything immediately, but just as a heads-up the old format is
  server {     listen      90.91.45.3:443 ssl http2;   
and the new format for nginx &gt;= 1.25.1 is
  server {     listen      90.91.45.3:443 ssl;     http2  on;  
希望更新一下生成的配置文件。

**Comment by 0x11901** [comment]
哦，看到了。不过说实话有点不方便，看起来需要每个都需要单独配置，选新版。

**Comment by ICEY16360** [comment]
确实不方便，请问能不能加个全局一键配置
