### ISSUE TITLE
垃圾垃圾垃圾 没测试就拿出来显世

### ISSUE THREAD

**Issue by valewu** [cym1102/nginxWebUI#154]
![屏幕截图 2024-06-17 152156](https://github.com/cym1102/nginxWebUI/assets/19722110/b53cafae-96a5-4c69-9833-98fc19d83767)

**Comment by valewu** [comment]
![image](https://github.com/cym1102/nginxWebUI/assets/19722110/37cde03e-e1b6-4423-8920-666684218b89)

**Comment by hsy-design** [comment]
你这种人还注册账号呢 你才是垃圾 人家开源公益招你惹你了 bybl

**Comment by klxyy** [comment]
这智商也是没谁了

**Comment by Jackie264** [comment]
> 这智商也是没谁了

+1
