### ISSUE TITLE
系统配置读取错误

### ISSUE THREAD

**Issue by xplainn** [cym1102/nginxWebUI#155]
我最开始的服务器配置是2C4G，后面更换成了4C16G，但此时的服务器配置显示并未变化
<img width="401" alt="屏幕截图 2024-06-17 174946" src="https://github.com/cym1102/nginxWebUI/assets/22995563/5f10c3aa-f977-4db7-8bc1-f85fa0892b4a">

**Comment by cym1102** [comment]
这个是从系统读取的，可能docker启动的时候缓存了cpu数量



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月17日(周一) 下午5:54
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cym1102/nginxWebUI] 系统配置读取错误 (Issue #155)




 
我最开始的服务器配置是2C4G，后面更换成了4C16G，但此时的服务器配置显示并未变化
 2024-06-17.174946.png (view on web)
