### ISSUE TITLE
4.1.6版本提示"/home/nginxWebUI/logs/error.log" failed

### ISSUE THREAD

**Issue by zhenrongz** [cym1102/nginxWebUI#156]
我的nginx的配置里面配的是：
error_log /home/nginxWebUI/log/error.log;
access_log /home/nginxWebUI/log/access.log;
挂载的目录也是log（目录和文件存在）

但是“校验文件”时，提示如下错误：

nginx -t -c /home/nginxWebUI/temp/nginx.conf -p /home/nginxWebUI/
校验失败
nginx: [alert] could not open error log file: open() "/home/nginxWebUI/logs/error.log" failed (2: No such file or directory)
nginx: the configuration file /home/nginxWebUI/temp/nginx.conf syntax is ok
2024/06/19 18:20:42 [emerg] 329#329: open() "/home/nginxWebUI/logs/error.log" failed (2: No such file or directory)
nginx: configuration file /home/nginxWebUI/temp/nginx.conf test failed

虽然将配置和挂载目录都改成logs可以解决问题，但是默认配置（http的简易配置向导）里面用的log目录。

**Comment by cym1102** [comment]
这个跟你nginx安装方式有关系，跟webui无关



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月19日(周三) 晚上6:24
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cym1102/nginxWebUI] 4.1.6版本提示"/home/nginxWebUI/logs/error.log" failed (Issue #156)




 
提示如下错误：
 nginx -t -c /home/nginxWebUI/temp/nginx.conf -p /home/nginxWebUI/
 校验失败
 nginx: [alert] could not open error log file: open() "/home/nginxWebUI/logs/error.log" failed (2: No such file or directory)
 nginx: the configuration file /home/nginxWebUI/temp/nginx.conf syntax is ok
 2024/06/19 18:20:42 [emerg] 329#329: open() "/home/nginxWebUI/logs/error.log" failed (2: No such file or directory)
 nginx: configuration file /home/nginxWebUI/temp/nginx.conf test failed
 
虽然改成logs目录可以解决问题，但是默认配置（http的简易配置向导）里面用的log目录。
 
error_log /home/nginxWebUI/log/error.log;
 access_log /home/nginxWebUI/log/access.log;

**Comment by zhenrongz** [comment]
我是从3.7.9的docker镜像升级上来的，原先用的是log目录没有问题。
另外升级后之前的配置没了，不知道其他人有没有这个情况。
抽空帮忙验证下，谢谢。

**Comment by cym1102** [comment]
之前3.x用的h2数据库, 4.x换sqlite了, 中间做了一次数据转换, 可能太过古老的版本转换有问题
