### ISSUE TITLE
cloudflare 证书申请成功，webui 显示失败

### ISSUE THREAD

**Issue by zaixi** [cym1102/nginxWebUI#158]
看起来是申请时的等待和webui的超时没有统一

![image](https://github.com/cym1102/nginxWebUI/assets/19380087/a426f7ef-74e8-4d18-85d9-174c38aec520)
![image](https://github.com/cym1102/nginxWebUI/assets/19380087/8ac9202c-626e-4ac9-988a-c829698d4aa3)
![image](https://github.com/cym1102/nginxWebUI/assets/19380087/8c37b591-2b67-4c3a-a78b-520d8472f87d)

**Comment by cym1102** [comment]
webui限定申请时间为5分钟, 可能acme.sh的超时时间要长一点, 但我觉得5分钟都太长了, 5分钟申请不下来可以自己检查一下
