### ISSUE TITLE
证书管理在4.2.0版本中，使用“DNS验证”无法获取证书

### ISSUE THREAD

**Issue by bangbang93** [cym1102/nginxWebUI#159]
给到的域名是
![image](https://github.com/user-attachments/assets/cb0f03e6-b74a-497f-954e-181b79402b23)
![image](https://github.com/user-attachments/assets/66d6b12f-af4a-4fd8-91ec-d620ca4ab0ed)
解析也已添加生效，但是CNAME后的域名是NXDomain，所以，续签时报错
![image](https://github.com/user-attachments/assets/b7ab1f50-10df-4342-9a38-d712110eb361)

**Comment by cym1102** [comment]
不知道你那边咋回事, 我测了我的域名, 续签正常

**Comment by bangbang93** [comment]
这域名解析出来是nxdomain，它正常吗

**Comment by cym1102** [comment]
正常



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月17日(周三) 中午12:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cym1102/nginxWebUI] 证书管理在4.2.0版本中，使用“DNS验证”无法获取证书 (Issue #159)




 
这域名解析出来是nxdomain，它正常吗

**Comment by bangbang93** [comment]
下一步我该怎么排查？

**Comment by cym1102** [comment]
要不你新建一个证书重新申请



***@***.***
 
发件人： bangbang93
发送时间： 2024-07-18 10:41
收件人： cym1102/nginxWebUI
抄送： cym1102; State change
主题： Re: [cym1102/nginxWebUI] 证书管理在4.2.0版本中，使用“DNS验证”无法获取证书 (Issue #159)
下一步我该怎么排查？

**Comment by bangbang93** [comment]
`HOME=/etc/nginxwebui /etc/nginxwebui/.acme.sh/acme.sh --renew --force -d <domain> --yes-I-know-dns-manual-mode-enough-go-ahead-please`
手动执行这个命令，并且设置TXT记录可以正常更新证书
所以`1aab8359-ed60-4b9b-aaa9-d365e4e79c66.acme.nginxwebui.cn`这个域是用来干什么的？

**Comment by cym1102** [comment]
之前设置dns txt方式是旧版申请方案，设置dns cname记录是新版方案，所以我让你重新建个证书来申请



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月18日(周四) 上午10:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cym1102/nginxWebUI] 证书管理在4.2.0版本中，使用“DNS验证”无法获取证书 (Issue #159)




 
HOME=/etc/nginxwebui /etc/nginxwebui/.acme.sh/acme.sh --renew --force -d <domain&gt; --yes-I-know-dns-manual-mode-enough-go-ahead-please
 手动执行这个命令，并且设置TXT记录可以正常更新证书
 所以1aab8359-ed60-4b9b-aaa9-d365e4e79c66.acme.nginxwebui.cn这个域是用来干什么的？

**Comment by bangbang93** [comment]
那等下次三个月后过期了s我再试试吧

**Comment by cym1102** [comment]
不用，你现在就可以改，这个证书免费的，随便你怎么申请，不用了就删，没有成本



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月18日(周四) 中午11:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cym1102/nginxWebUI] 证书管理在4.2.0版本中，使用“DNS验证”无法获取证书 (Issue #159)




 
那等下次三个月后过期了s我再试试吧
