### ISSUE TITLE
容器中运行时，不能正常转发

### ISSUE THREAD

**Issue by longxinglxl** [cym1102/nginxWebUI#161]
我有两个容器分别运行着前后端项目，使用本项目的容器版本做反向代理，发现一个很奇怪的问题，做前端转发的时候在局域网内访问宿主机ip+映射的端口访问失败，在路由器上做了端口映射却能正常访问；后在在宿主机上直接安装的nginx复制本项目的配置，运行后都能正常访问。防火墙等安全措施已全部关闭还不能正常访问。
这是容器运行状态
![image](https://github.com/user-attachments/assets/3ae8e0ad-2def-4bfd-9c4a-62c420cb0b04)
局域网内页面访问状态
![image](https://github.com/user-attachments/assets/fb2ff3fe-55dd-4030-bf93-af291cc5f9fa)
端口映射记录
![image](https://github.com/user-attachments/assets/677aec4a-424c-417d-ac2e-97ce9f556daf)
端口映射后能正常访问 
![image](https://github.com/user-attachments/assets/9f6e0de2-c400-4483-b7f9-5532050c601f)
nginxwebui配置
`load_module /usr/lib/nginx/modules/ngx_stream_module.so;
worker_processes auto;
events {
    worker_connections  1024;
    accept_mutex on;
  }
http {
  error_log /opt/nginxwebui/log/error.log;
  map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
  }
  access_log /opt/nginxwebui/log/access.log;
  keepalive_timeout 75s;
  gzip on;
  gzip_min_length 4k;
  gzip_comp_level 4;
  client_max_body_size 10m;
  client_header_buffer_size 32k;
  client_body_buffer_size 8m;
  server_names_hash_bucket_size 512;
  proxy_headers_hash_max_size 51200;
  proxy_headers_hash_bucket_size 6400;
  gzip_types application/javascript application/x-javascript text/javascript text/css application/json application/xml;
  include mime.types;
  default_type application/octet-stream;
  server {
    server_name _;
    listen 80;
    listen [::]:80;
    location /api {
      proxy_pass http://192.168.9.12:8080;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Host $http_host;
      proxy_set_header X-Forwarded-Port $server_port;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      add_header Access-Control-Allow-Origin *;
      add_header Access-Control-Allow-Methods *;
      add_header Access-Control-Allow-Headers *;
      add_header Access-Control-Allow-Credentials true;
      if ($request_method = 'OPTIONS') {
        return 204;
      }
      proxy_set_header X-Original-URI $request_uri;
    }
    location / {
      proxy_pass http://192.168.9.12:2080;
    }
  }
}
`

**Comment by cym1102** [comment]
那就不要用docker直接用jar启动吧, docker里面的网络环境还是比较复杂的
