### ISSUE TITLE
更新到4.2.2版本后，出现用户名密码错误

### ISSUE THREAD

**Issue by Lizhen0628** [cym1102/nginxWebUI#162]
更新到4.2.2版本后，出现用户名密码错误。
密码：qJ2d7cjf4S^pvB

**Comment by cym1102** [comment]
之前上传了一次错误的4.2.2代码, 后来又修正了, 要不你重新拉一下jar或镜像试试, 要不等会我去发个4.2.3, 彻底覆盖4.2.2的问题



***@***.***
 
发件人： LiZhen
发送时间： 2024-07-31 10:27
收件人： cym1102/nginxWebUI
抄送： Subscribed
主题： [cym1102/nginxWebUI] 更新到4.2.2版本后，出现用户名密码错误 (Issue #162)
更新到4.2.2版本后，出现用户名密码错误。
密码：qJ2d7cjf4S^pvB
