### ISSUE TITLE
建议增加面板根路径，方便面板通过location反代

### ISSUE THREAD

**Issue by PR2403** [cym1102/nginxWebUI#165]
目前面板的静态资源没有统一的根路径，导致无法方便的使用location反代，虽然可以使用第二个域名反代
建议为面板所有的资源添加一个根路径，像xui面板这样的选项
![image](https://github.com/user-attachments/assets/fde8f169-a57d-4bef-aa46-351c1e4c1860)
最后感谢开发这样一个方便使用的webui，配置省了不少事

**Comment by cym1102** [comment]
没懂, 所有nginx参数你都可以自己配, 想怎么配就怎么配

**Comment by PR2403** [comment]
> 没懂, 所有nginx参数你都可以自己配, 想怎么配就怎么配

只是希望从同一域名下的不同路径访问面板，面板后端做了重定向但没有一个总的根路径导致没法代理静态资源

**Comment by cym1102** [comment]
做不到,框架定死了



***@***.***
 
发件人： PR2403
发送时间： 2024-09-24 16:41
收件人： cym1102/nginxWebUI
抄送： cym1102; State change
主题： Re: [cym1102/nginxWebUI] 建议增加面板根路径，方便面板通过location反代 (Issue #165)
没懂, 所有nginx参数你都可以自己配, 想怎么配就怎么配
只是希望从同一域名下的不同路径访问面板，面板后端做了重定向但没有一个总的根路径导致没法代理静态资源
