### ISSUE TITLE
nginxWebUI-Pro docker 启动失败

### ISSUE THREAD

**Issue by MJ-spmoon** [cym1102/nginxWebUI#169]
启动报错，日志显示：

![20240924](https://github.com/user-attachments/assets/0a68c3c4-44b8-4bae-82e0-f73bd0348f81)

Cannot start server. You can execute sudo --preserve-env -u 'clickhouse' /usr/bin/clickhouse-server --config-file /etc/clickhouse-server/config.xml --pid-file /var/run/clickhouse-server/clickhouse-server.pid --daemon without --daemon option to run manually.

Look for logs at /home/nginxWebUI-Pro/clickhouse/log/ and for /home/nginxWebUI-Pro/clickhouse/log/stderr.log.
chown -R clickhouse: '/var/run/clickhouse-server/'

Will run sudo --preserve-env -u 'clickhouse' /usr/bin/clickhouse-server --config-file /etc/clickhouse-server/config.xml --pid-file /var/run/clickhouse-server/clickhouse-server.pid --daemon

**Comment by cym1102** [comment]
我看看

**Comment by cym1102** [comment]
我拉最新版镜像没有报错, 你按官网命令重新拉镜像启动
