### ISSUE TITLE
修改/home/nginxWebUI/mime.types，重新加载配置的时候被覆盖了

### ISSUE THREAD

**Issue by passiolin** [cym1102/nginxWebUI#173]
我们前端想加个mime类型，mjs，之前旧版本的时候，我是直接改/home/nginxWebUI/mime.types的配置文件的。
![图片](https://github.com/user-attachments/assets/074ec186-cb5a-4433-9516-ff0479911e96)

但是升级到最新版本之后，每次重新重载配置，/home/nginxWebUI/mime.types就会被覆盖。

我看了下代码，是4.0.9的时候做了这个改动，将/etc/nginx/mime.types替换成了/home/nginxWebUI/mime.types
![图片](https://github.com/user-attachments/assets/3ba0cbf1-0c57-4cbf-b12b-983f64516ac1)
![图片](https://github.com/user-attachments/assets/43fabdcc-9257-4fc5-8be1-cef29eb78e94)

我有几个问题：
1、4.0.9出于什么样的考虑做这样的改动？
2、开发人员是否认为是bug？后续是否考虑修复？

**Comment by cym1102** [comment]
你加在include mine.types那一行的后面就可以了, mine.types这个文件最好不要动
---- 回复的原邮件 ----
***@***.***>发送日期2024年11月7日 ***@***.***>***@***.***>主题[cym1102/nginxWebUI] 修改/home/nginxWebUI/mime.types，重新加载配置的时候被覆盖了 (Issue #173)
我们前端想加个mime类型，mjs，之前旧版本的时候，我是直接改/home/nginxWebUI/mime.types的配置文件的。
default.png (view on web)
但是升级到最新版本之后，每次重新重载配置，/home/nginxWebUI/mime.types就会被覆盖。
我看了下代码，是4.0.9的时候做了这个改动，将/etc/nginx/mime.types替换成了/home/nginxWebUI/mime.types
default.png (view on web)
default.png (view on web)
我有几个问题：
1、4.0.9出于什么样的考虑做这样的改动？
2、开发人员是否认为是bug？后续是否考虑修复？

**Comment by passiolin** [comment]
好的

**Comment by passiolin** [comment]
> 你加在include mine.types那一行的后面就可以了, mine.types这个文件最好不要动 ---- 回复的原邮件 ---- ***@***.***>发送日期2024年11月7日 ***@***.***>***@***.***>主题[cym1102/nginxWebUI] 修改/home/nginxWebUI/mime.types，重新加载配置的时候被覆盖了 (Issue #173) 我们前端想加个mime类型，mjs，之前旧版本的时候，我是直接改/home/nginxWebUI/mime.types的配置文件的。 default.png (view on web) 但是升级到最新版本之后，每次重新重载配置，/home/nginxWebUI/mime.types就会被覆盖。 我看了下代码，是4.0.9的时候做了这个改动，将/etc/nginx/mime.types替换成了/home/nginxWebUI/mime.types default.png (view on web) default.png (view on web) 我有几个问题： 1、4.0.9出于什么样的考虑做这样的改动？ 2、开发人员是否认为是bug？后续是否考虑修复？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

好的
