### ISSUE TITLE
能否支持一个系统环境下运行两个nginxWebUI.jar进程

### ISSUE THREAD

**Issue by JessicaQling** [cym1102/nginxWebUI#26]
尝试在同一台物理机上启动两个nginxWebUI.jar进程，server.port和project.home做了区分，启动第二个进程时会导致第一个进程退出

**Comment by cym1102** [comment]
可以, 要改下代码, 本来这玩意是设计成单实例的, 你把NginxWebUI.java里的killSelf()注释掉就行了.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cym1102/nginxWebUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月28日(星期二) 下午4:30
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[cym1102/nginxWebUI] 能否支持一个系统环境下运行两个nginxWebUI.jar进程 (Issue #26)





 
尝试在同一台物理机上启动两个nginxWebUI.jar进程，server.port和project.home做了区分，启动第二个进程时会导致第一个进程退出
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JessicaQling** [comment]
可以下个版本支持吗？

**Comment by cym1102** [comment]
这种工具型软件一般都是单进程，不做多进程。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月28日(周二) 晚上6:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cym1102/nginxWebUI] 能否支持一个系统环境下运行两个nginxWebUI.jar进程 (Issue #26)




 
可以下个版本支持吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
