### ISSUE TITLE
怎么做到 sqlite 无需安装即可使用的？

### ISSUE THREAD

**Issue by zhixiangyuan** [cym1102/nginxWebUI#27]
sqlite 不是也需要安装么？为什么这个项目做到了不安装 sqlite 即可使用，是代码里面有自动安装的脚本么？但是我在代码里面没有看到相关的自动安装脚本。

**Comment by cym1102** [comment]
就是解压一个sqlite.db到硬盘上就行了, java有sqlite驱动就能读取sqlite.db文件




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cym1102/nginxWebUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月29日(星期三) 下午5:45
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[cym1102/nginxWebUI] 怎么做到 sqlite 无需安装即可使用的？ (Issue #27)





 
sqlite 不是也需要安装么？为什么这个项目做到了不安装 sqlite 即可使用，是代码里面有自动安装的脚本么？但是我在代码里面没有看到相关的自动安装脚本。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhixiangyuan** [comment]
了解了，centos 自带 sqlite3，谢谢
