### ISSUE TITLE
更新3.0.7后全部中文乱码

### ISSUE THREAD

**Issue by mxlt02** [cym1102/nginxWebUI#31]
![image](https://user-images.githubusercontent.com/57489136/151651500-4baf2a46-87bd-4392-88c2-5180b4d7f803.png)
![image](https://user-images.githubusercontent.com/57489136/151651507-fa374b11-76e2-4980-94cc-c99545511bf7.png)
ubuntu.docker

**Comment by cym1102** [comment]
把docker镜像更新就行了，底包换成alpine了，占用更小。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月29日(周六) 下午3:10
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cym1102/nginxWebUI] 更新3.0.7后全部中文乱码 (Issue #31)




 

 
 ubuntu.docker
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
