### ISSUE TITLE
3.1.0 bug

### ISSUE THREAD

**Issue by zhixiangyuan** [cym1102/nginxWebUI#33]
# 现象

升级最新版之后无法访问页面

![image](https://user-images.githubusercontent.com/25138766/152734629-1024c46b-c2ab-4a2a-9cb8-4812aa57d862.png)

# 原因

我给 nginxWebUI 控制台配置的是 https，但是发起的请求却是 http，导致浏览器不发请求

![image](https://user-images.githubusercontent.com/25138766/152734591-0a93c835-7d5d-4e9e-bee7-73c5b2be4505.png)

![image](https://user-images.githubusercontent.com/25138766/152734806-9d60df22-429c-49a1-8f8d-cb3b3d60cfbd.png)

![image](https://user-images.githubusercontent.com/25138766/152734954-fdae6804-69f3-499b-a8da-8e5e92e1f2b1.png)

**Comment by cym1102** [comment]
明白了，等我改一下



---Original---
From: ***@***.***&gt;
Date: Mon, Feb 7, 2022 14:19 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [cym1102/nginxWebUI] 3.1.0 bug (Issue #33)




 
现象
 
升级最新版之后无法访问页面
 

 
原因
 
我给 nginxWebUI 控制台配置的是 https，但是发起的请求却是 http，导致浏览器不发请求
 

 

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cym1102** [comment]
好了, 升级3.1.1试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cym1102/nginxWebUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月7日(星期一) 下午2:19
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[cym1102/nginxWebUI] 3.1.0 bug (Issue #33)





 
现象
 
升级最新版之后无法访问页面
 

 
原因
 
我给 nginxWebUI 控制台配置的是 https，但是发起的请求却是 http，导致浏览器不发请求
 

 

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhixiangyuan** [comment]
老哥牛逼，完美运行
