### ISSUE TITLE
乱码

### ISSUE THREAD

**Issue by SuzukazeHaruka** [cym1102/nginxWebUI#35]
启动后页面出现中文乱码问题

**Comment by cym1102** [comment]
nohup java -jar -Dfile.encoding=UTF-8 /home/nginxWebUI/nginxWebUI.jar --server.port=8080 --project.home=/home/nginxWebUI/ &gt; /dev/null &amp;注意启动命令有没有加 -Dfile.encoding=UTF-8 参数




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cym1102/nginxWebUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月24日(星期四) 下午2:07
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[cym1102/nginxWebUI] 乱码 (Issue #35)





 
启动后页面出现中文乱码问题
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SuzukazeHaruka** [comment]
win11环境下最新版使用命令 jar -jar nginxWebUI.jar --Dfile.encoding=UTF-8  还是出现乱码
![image](https://user-images.githubusercontent.com/43751174/155469586-de2a8d66-378d-466d-aef1-624bf334114a.png)
使用2.8.8版本正常,3.1.7版本不行

**Comment by cym1102** [comment]
-Dfile.encoding=UTF-8&nbsp; 注意只有一个横杠




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月24日(星期四) 下午2:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cym1102/nginxWebUI] 乱码 (Issue #35)





 
win11环境下最新版使用命令 jar -jar nginxWebUI.jar --Dfile.encoding=UTF-8  还是出现乱码
 
 使用2.8.8版本正常,3.1.7版本不行
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SuzukazeHaruka** [comment]
-Dfile.encoding=UTF-8 与--Dfile.encoding=UTF-8都试了一下还是乱码

**Comment by cym1102** [comment]
我还没有win11环境, 我测试一下再说




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月24日(星期四) 下午2:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cym1102/nginxWebUI] 乱码 (Issue #35)





 
-Dfile.encoding=UTF-8 与--Dfile.encoding=UTF-8都试了一下还是乱码
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cym1102** [comment]
3.1.8已解决此bug

**Comment by ddddk1245** [comment]
-Dfile.encoding=UTF-8必须放在前面，如下这样才可以，放在中间或最后就无效。。
java -jar -Dfile.encoding=UTF-8

**Comment by cym1102** [comment]
我说明上面就是这样写的啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月24日(星期一) 下午2:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [cym1102/nginxWebUI] 乱码 (Issue #35)





 
-Dfile.encoding=UTF-8必须放在前面，如下这样才可以，放在中间或最后就无效。。
 java -jar -Dfile.encoding=UTF-8
