### ISSUE TITLE
是否可以支持ecc证书呢

### ISSUE THREAD

**Issue by isdamir** [cym1102/nginxWebUI#39]
能否支持ecc证书申请，并且可以增加想到配置启用双证书呢。
<img width="422" alt="image" src="https://user-images.githubusercontent.com/1901709/159224642-5f792174-d10c-491b-a3fb-bfd7a9999acf.png">

**Comment by cym1102** [comment]
暂不支持其他证书，双证书你可以尝试使用额外参数添加



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月21日(周一) 下午4:15
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cym1102/nginxWebUI] 是否可以支持ecc证书呢 (Issue #39)




 
能否支持ecc证书申请，并且可以增加想到配置启用双证书呢。
 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by isdamir** [comment]
参数配置本身倒不是问题，主要是申请这里，申请能否我自己增加配置呢。

**Comment by cym1102** [comment]
我不太懂如何用acme.sh去申请ecc证书. 如果你能提供一下申请方法, 也许我可以集成进去



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月21日(星期一) 下午4:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cym1102/nginxWebUI] 是否可以支持ecc证书呢 (Issue #39)





 
参数配置本身倒不是问题，主要是申请这里，申请能否我自己增加配置呢。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by isdamir** [comment]
可以在原本的申请命令结尾增加参数` --keylength ec-256`即可，可以保存到不同目录或者不同文件名即可
`acme.sh --issue -w /home/wwwroot/example.com -d example.com --keylength ec-256`

nginx设置双证书方式如下，配置两个即可
`        ##
        # SSL Settings
        ##
        # ecc certificate
        ssl_certificate /etc/ssl/acme/nginx_ecc/cert.pem;
        ssl_certificate_key  /etc/ssl/acme/nginx_ecc/key.pem;
        # rsa certificate
        ssl_certificate  /etc/ssl/acme/nginx/cert.pem;
        ssl_certificate_key /etc/ssl/acme/nginx/key.pem;`

**Comment by isdamir** [comment]
ecc可选长度参数如下：
可选长度有：
```
ec-256 (prime256v1, “ECDSA P-256”)
ec-384 (secp384r1, “ECDSA P-384”)
ec-521 (secp521r1, “ECDSA P-521”, which is not supported by Let’s Encrypt yet.)
```

**Comment by cym1102** [comment]
那我下个版本给你加上去




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月21日(星期一) 下午4:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cym1102/nginxWebUI] 是否可以支持ecc证书呢 (Issue #39)





 
可以在原本的申请命令结尾增加参数 --keylength ec-256即可，可以保存到不同目录或者不同文件名即可
 acme.sh --issue -w /home/wwwroot/example.com -d example.com --keylength ec-256
 
nginx设置双证书方式如下，配置两个即可
         ## # SSL Settings ## # ecc certificate ssl_certificate /etc/ssl/acme/nginx_ecc/cert.pem; ssl_certificate_key  /etc/ssl/acme/nginx_ecc/key.pem; # rsa certificate ssl_certificate  /etc/ssl/acme/nginx/cert.pem; ssl_certificate_key /etc/ssl/acme/nginx/key.pem;
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by isdamir** [comment]
非常感谢，另外不知道有没有人有http保持端口不变跳转https的需求，我看当前生成自动跳转是要不同端口的。如果加这个我可以fork增加吗。

**Comment by cym1102** [comment]
可以自己写if语句, 制作成模板自己用




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月21日(星期一) 下午4:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cym1102/nginxWebUI] 是否可以支持ecc证书呢 (Issue #39)





 
非常感谢，另外不知道有没有人有http保持端口不变跳转https的需求，我看当前生成自动跳转是要不同端口的。如果加这个我可以fork增加吗。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by isdamir** [comment]
OK，我自己用倒是简单。

**Comment by isdamir** [comment]
我更新了3.2.2版本，没有找到ECC的证书申请设置在哪里呢？
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/1901709/159433171-f517783e-84f6-444d-b28d-c0e1075deb38.png">

**Comment by cym1102** [comment]
默认申请就是ecc, 不需要手动配




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月22日(星期二) 下午3:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cym1102/nginxWebUI] 是否可以支持ecc证书呢 (Issue #39)





 
我更新了3.2.2版本，没有找到ECC的证书申请设置在哪里呢？

**Comment by isdamir** [comment]
不能通过参数控制申请双证书吗，双证书对于老浏览器兼容性更好。

**Comment by cym1102** [comment]
这个需求太小众了, 你需要的话就自己用模板配吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月22日(星期二) 下午3:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cym1102/nginxWebUI] 是否可以支持ecc证书呢 (Issue #39)





 
不能通过参数控制申请双证书吗，双证书对于老浏览器兼容性更好。

**Comment by isdamir** [comment]
配置倒是没问题的，主要是申请是需要申请到两份，两份pem和key文件不一样。

**Comment by cym1102** [comment]
同一个域名申请两个证书?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月22日(星期二) 下午3:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cym1102/nginxWebUI] 是否可以支持ecc证书呢 (Issue #39)





 
配置倒是没问题的，主要是申请是需要申请到两份，两份pem和key文件不一样。

**Comment by isdamir** [comment]
对，是可以的，let's encrypt 支持同一个域名申请RSA和ECC双证书，配置双证书后通过https://myssl.com/可以检测到，浏览器会自行选择。可以最大幅度提高兼容性。

**Comment by cym1102** [comment]
我明白了你的意思了, 证书申请类型可选这个好实现, 但给域名配双证书, 还得是需要你用模板配了, 我下个版本加上选择证书申请类型




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月22日(星期二) 下午4:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cym1102/nginxWebUI] 是否可以支持ecc证书呢 (Issue #39)





 
对，是可以的，let's encrypt 支持同一个域名申请RSA和ECC双证书，配置双证书后通过https://myssl.com/可以检测到，浏览器会自行选择。可以最大幅度提高兼容性。

**Comment by isdamir** [comment]
这个没问题，我通过模版配置到所有http里面即可。

**Comment by isdamir** [comment]
不过我刚发现，更新了新版本后直接续签后还是RSA的证书。

**Comment by isdamir** [comment]
<img width="639" alt="image" src="https://user-images.githubusercontent.com/1901709/159435286-ca8b144c-5123-44c5-b040-6582c431772e.png">

**Comment by cym1102** [comment]
旧的证书续签还是RSA, 因为申请的时候就确定是RSA了, 要重新申请才是ECC



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月22日(星期二) 下午4:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cym1102/nginxWebUI] 是否可以支持ecc证书呢 (Issue #39)





 
不过我刚发现，更新了新版本后直接续签后还是RSA的证书。

**Comment by isdamir** [comment]
OK。了解了
