### ISSUE TITLE
建议增加cloudflare dns服务商

### ISSUE THREAD

**Issue by Mircc** [cym1102/nginxWebUI#4]
很多域名都在这个dns服务商那里，希望大大能增加

**Comment by cym1102** [comment]
好的,&nbsp;我研究一下,&nbsp;下个版本可能能上




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cym1102/nginxWebUI"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月31日(星期一) 中午11:44
收件人:&nbsp;"cym1102/nginxWebUI"<nginxWebUI@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[cym1102/nginxWebUI] 建议增加cloudflare dns服务商 (#4)





 
很多域名都在这个dns服务商那里，希望大大能增加

**Comment by cym1102** [comment]
1.9.4已加入cloudflare, 自动更新即可, 但我没有上面的域名, 可否测试一下,再反馈给我
