### ISSUE TITLE
Cloudflare的DNS验证是否能跟改为API令牌

### ISSUE THREAD

**Issue by zhangyiqiu** [cym1102/nginxWebUI#40]
![image](https://user-images.githubusercontent.com/22910338/160236772-70275afd-0793-4412-8b2a-fbfe09617196.png)
API令牌可以控制API的权限
而EMAIL+KEY的方式好像没办法控制权限

**Comment by cym1102** [comment]
我先学习一下再说，我对cf不太熟



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月26日(周六) 晚上7:11
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cym1102/nginxWebUI] Cloudflare的DNS验证是否能跟改为API令牌 (Issue #40)




 

 API令牌可以控制API的权限
 而EMAIL+KEY的方式好像没办法控制权限

**Comment by zhangyiqiu** [comment]
acme是支持这种方式的
https://github.com/acmesh-official/acme.sh/wiki/dnsapi#using-the-new-cloudflare-api-token-you-will-get-this-after-normal-login-and--scroll-down-on-dashboard-and-copy-credentials

**Comment by YipSzeho** [comment]
请问现在webui申请cf的证书，用的是global key吗，我用global key会显示超时
