### ISSUE TITLE
try files support

### ISSUE THREAD

**Issue by sjfbjs** [cym1102/nginxWebUI#42]
目前是否支持单页面的配置？ 本人修改了部分源码支持了单页面的配置生成等

**Comment by cym1102** [comment]
你可以提交pr试试



---Original---
From: ***@***.***&gt;
Date: Wed, May 18, 2022 16:04 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [cym1102/nginxWebUI] try files support (Issue #42)




 
目前是否支持单页面的配置？ 本人修改了部分源码支持了单页面的配置生成等
