### ISSUE TITLE
希望增加一下二级域名的支持

### ISSUE THREAD

**Issue by 0x11901** [cym1102/nginxWebUI#43]
二级域名还是有需求的，感觉目前没找到哪里可以简单的配置

**Comment by cym1102** [comment]
二级域名你自己在域名监听里配就行了啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cym1102/nginxWebUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月7日(星期二) 晚上6:39
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[cym1102/nginxWebUI] 希望增加一下二级域名的支持 (Issue #43)





 
二级域名还是有需求的，感觉目前没找到哪里可以简单的配置

**Comment by 0x11901** [comment]
但是我没有在哪里找到有域名监听的配置选项阿，平时我也没有用过nginx，就是想简单一点才使用这个web ui的

反正对于初学者来说想要实现这个功能感觉不是很方便阿

**Comment by cym1102** [comment]
可以看看这个视频教程
https://www.bilibili.com/video/BV18A4y1D7GZ?spm_id_from=333.337.search-card.all.click




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月8日(星期三) 下午3:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cym1102/nginxWebUI] 希望增加一下二级域名的支持 (Issue #43)





 
但是我没有在哪里找到有域名监听的配置选项阿，平时我也没有用过nginx，就是想简单一点才使用这个web ui的
 
反正对于初学者来说想要实现这个功能感觉不是很方便阿

**Comment by 0x11901** [comment]
> 可以看看这个视频教程 https://www.bilibili.com/video/BV18A4y1D7GZ?spm_id_from=333.337.search-card.all.click
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年6月8日(星期三) 下午3:31 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [cym1102/nginxWebUI] 希望增加一下二级域名的支持 (Issue #43) 但是我没有在哪里找到有域名监听的配置选项阿，平时我也没有用过nginx，就是想简单一点才使用这个web ui的 反正对于初学者来说想要实现这个功能感觉不是很方便阿 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

说实话还是没看懂……难道是那个负载……

**Comment by 0x11901** [comment]
我明白了（
