### ISSUE TITLE
请遵原始项目的循GPL协议

### ISSUE THREAD

**Issue by onlyGuo** [cym1102/nginxWebUI#44]
请遵原始项目的循GPL协议： [https://github.com/onlyGuo/nginx-gui/blob/master/LICENSE](https://gitee.com/link?target=https%3A%2F%2Fgithub.com%2FonlyGuo%2Fnginx-gui%2Fblob%2Fmaster%2FLICENSE)
任何起于GPL开源协议的原始项目的迭代或变更都应继续采用GPL协议。

**Comment by cym1102** [comment]
我的项目是从头写的, 不是基于这个项目
