### ISSUE TITLE
泛域名证书问题

### ISSUE THREAD

**Issue by MINIPuffer** [cym1102/nginxWebUI#45]
版本：3.3.5
申请泛域名证书时配置的域名为：`*.xxxx.com`
自动配置的证书名为：`*.xxxx.com.fullchain.cer`
但实际生成的证书名为：`.xxxx.com.fullchain.cer`
这就导致nginx找不到证书，每次都要都手动改

**Comment by cym1102** [comment]
我这边申请出来确实是*号开头的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cym1102/nginxWebUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月5日(星期二) 下午3:43
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[cym1102/nginxWebUI] 泛域名证书问题 (Issue #45)





 
版本：3.3.5
 申请泛域名证书时配置的域名为：*.xxxx.com
 自动配置的证书名为：*.xxxx.com.fullchain.cer
 但实际生成的证书名为：.xxxx.com.fullchain.cer
 这就导致nginx找不到证书，每次都要都手动改

**Comment by cym1102** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cym1102/nginxWebUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月5日(星期二) 下午3:43
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[cym1102/nginxWebUI] 泛域名证书问题 (Issue #45)





 
版本：3.3.5
 申请泛域名证书时配置的域名为：*.xxxx.com
 自动配置的证书名为：*.xxxx.com.fullchain.cer
 但实际生成的证书名为：.xxxx.com.fullchain.cer
 这就导致nginx找不到证书，每次都要都手动改

**Comment by MINIPuffer** [comment]
续签的时候呢，我是续签出现了这个问题

**Comment by cym1102** [comment]
续签不会改动文件路径




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月5日(星期二) 下午3:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cym1102/nginxWebUI] 泛域名证书问题 (Issue #45)





 
续签的时候呢，我是续签出现了这个问题

**Comment by MINIPuffer** [comment]
好的，谢谢，后续如果有复现我再提
