### ISSUE TITLE
中文乱码

### ISSUE THREAD

**Issue by LIHONGYUANYUAN** [cym1102/nginxWebUI#48]
请问的我乱码是什么情况呢
![image](https://user-images.githubusercontent.com/37687744/191150365-a3a9a1cf-e54e-4782-a015-4daba61e5fba.png)

**Comment by cym1102** [comment]
启动参数没有写全，你再仔细看看官网启动参数



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月20日(周二) 上午9:57
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cym1102/nginxWebUI] 中文乱码 (Issue #48)




 
请问的我乱码是什么情况呢

**Comment by KimMeng2015** [comment]
windows 上安装的，也乱码了 可能是啥原因

**Comment by cym1102** [comment]
都是字符集参数没有填写



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月20日(周二) 上午10:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cym1102/nginxWebUI] 中文乱码 (Issue #48)




 
windows 上安装的，也乱码了 可能是啥原因

**Comment by LIHONGYUANYUAN** [comment]
照文档的语句写，OK了，谢谢
java -jar -Dfile.encoding=UTF-8 D:/home/nginxWebUI/nginxWebUI.jar --server.port=8080 --project.home=D:/home/nginxWebUI/
