### ISSUE TITLE
docker安装owncloud 反代

### ISSUE THREAD

**Issue by jack338c** [cym1102/nginxWebUI#49]
大神好！
刚刚在使用您的nginxWebUI,但是反代总是不成功，请帮看下问题出在哪里

#Doker owncloud 安装在omv机器上，安装omv时自动安装了nginx ,owncloud登录地址10.20.30.150:8082
docker run -d \ --name=owncloud \ -e OWNCLOUD_DOMAIN=localhost:8082 \ -p 8082:8080 \ -v /mnt/owncloud:/mnt/data \ --restart unless-stopped \ owncloud/server:latest
#nginxWebUI的web端口是9080
配置如图
![Screen Shot 2022-09-24 at 12 13 29 PM](https://user-images.githubusercontent.com/10782586/192079522-5086b3e9-4516-46ad-a737-0c8e1d25dad7.png)
![Screen Shot 2022-09-24 at 12 14 38 PM](https://user-images.githubusercontent.com/10782586/192079525-00b09723-b286-47a3-a6d2-d19bd12a2399.png)
路由器端口转发10.20.30.150:8082 到公网（xx.yyy.cn):8443
打开xx.yyy.cn:8443结果如下图(端口转发到10.20.30.150:8443也是一样结果)
![Screen Shot 2022-09-24 at 12 21 54 PM](https://user-images.githubusercontent.com/10782586/192079722-1e319a08-b324-4f36-86c9-10ae2e5fefb2.png)

**Comment by cym1102** [comment]
docker里已经安装了nginx，不需要外部再安装一个nginx，docker操作也只能操作自己内部的nginx



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月24日(周六) 中午12:23
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cym1102/nginxWebUI] docker安装owncloud 反代 (Issue #49)




 
大神好！
 刚刚在使用您的nginxWebUI,但是反代总是不成功，请帮看下问题出在哪里
 
#Doker owncloud 安装在omv机器上，安装omv时自动安装了nginx ,owncloud登录地址10.20.30.150:8082
 docker run -d \ --name=owncloud \ -e OWNCLOUD_DOMAIN=localhost:8082 \ -p 8082:8080 \ -v /mnt/owncloud:/mnt/data \ --restart unless-stopped \ owncloud/server:latest
 #nginxWebUI的web端口是9080
 配置如图
 
 
 路由器端口转发10.20.30.150:8082 到公网（xx.yyy.cn):8443
 打开xx.yyy.cn:8443结果如下图(端口转发到10.20.30.150:8443也是一样结果)

**Comment by jack338c** [comment]
确实如您说的
![Screen Shot 2022-09-24 at 12 43 16 PM](https://user-images.githubusercontent.com/10782586/192080397-08b82f5c-afa0-4fa7-bfc2-1d96529625de.png)

但是我不知道怎么修改,按下面链接的教程可以吗？，或者您方便teamviewer或者todesk远程帮我解决吗（OMV是armbian系统，h96max)
[https://blog.csdn.net/u010521588/article/details/123208313](url)

**Comment by cym1102** [comment]
暂时没有空，你看看在网页上重启nginx试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月24日(周六) 中午12:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cym1102/nginxWebUI] docker安装owncloud 反代 (Issue #49)




 
确实如您说的
 
 
但是我不知道怎么修改,按下面链接的教程可以吗？，或者您方便teamviewer或者todesk远程帮我解决吗（OMV是armbian系统，h96max)
 https://blog.csdn.net/u010521588/article/details/123208313

**Comment by jack338c** [comment]
> 
感谢！
wechatID  jack338c

**Comment by jack338c** [comment]
@cym1102 
[https://github.com/owncloud-docker/server/issues/89](url)

The SSL functionality have been dropped recently. The container is listening to 8080 only now.

If you want to customize the image to get back ssl termination you can overwrite https://github.com/owncloud-docker/base/blob/master/rootfs/etc/templates/apache.conf and https://github.com/owncloud-docker/php/blob/master/rootfs/etc/apache2/ports.con.

But anyway we suggest to use a reverse proxy like nginx, haproxy or traefik for SSL termination.
