### ISSUE TITLE
nginxWebUI 自身怎么应用ssl?

### ISSUE THREAD

**Issue by jian263994241** [cym1102/nginxWebUI#51]
需要设置成 https 外链 nginxWebUI 管理页面

**Comment by cym1102** [comment]
还是通过nginx代理，在绑上ssl证书啊



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月31日(周一) 下午4:59
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cym1102/nginxWebUI] nginxWebUI 自身怎么应用ssl? (Issue #51)




 
需要设置成 https 外链 nginxWebUI 管理页面
