### ISSUE TITLE
https跳轉設置建議

### ISSUE THREAD

**Issue by stevenwdhu** [cym1102/nginxWebUI#54]
<img width="571" alt="image" src="https://user-images.githubusercontent.com/30546031/202955180-5c8bcd21-5a6b-4bf8-81dc-4e89b4eef306.png">
對此項設置有以下建議：
1. 該設置實際含義為「從此處設置的端口跳轉至正在監聽的域名端口」，但是從設置的表述中較難看出實際含義，希望可以更改一下表述，如「http監聽端口」或「從該端口跳轉」。
2. 對於使用了端口轉發的情形，所監聽的端口並不等於訪問的端口，此時不能自定義跳轉的端口會造成一些額外的麻煩，希望可以自定義跳轉至的端口（如果可以同時增加http code和域名的自定義功能會更好）

**Comment by cym1102** [comment]
收到, 有时间会修改
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cym1102/nginxWebUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月21日(星期一) 中午12:37
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[cym1102/nginxWebUI] https跳轉設置建議 (Issue #54)





 

 對此項設置有以下建議： 1. 該設置實際含義為「從此處設置的端口跳轉至正在監聽的域名端口」，但是從設置的表述中較難看出實際含義，希望可以更改一下表述，如「http監聽端口」或「從該端口跳轉」。 2. 對於使用了端口轉發的情形，所監聽的端口並不等於訪問的端口，此時不能自定義跳轉的端口會造成一些額外的麻煩，希望可以自定義跳轉至的端口（如果可以同時增加http code和域名的自定義功能會更好）
