### ISSUE TITLE
能支持 context-path 吗

### ISSUE THREAD

**Issue by amwu** [cym1102/nginxWebUI#56]
Solon v1.11.2 后配置支持
http://solon.noear.org/article/216

**Comment by cym1102** [comment]
不支持



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月29日(周二) 上午9:19
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cym1102/nginxWebUI] 能支持 context-path 吗 (Issue #56)




 
Solon v1.11.2 后配置支持
 http://solon.noear.org/article/216
