### ISSUE TITLE
怎么迁移证书?

### ISSUE THREAD

**Issue by jian263994241** [cym1102/nginxWebUI#59]
目前备份配置, 不包含证书.   

目前方案是重新申请一次证书,  比较麻烦,  能包含在备份配置里吗?

**Comment by cym1102** [comment]
不好做,证书一系列配套是存在acme里面的, 不好做备份




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cym1102/nginxWebUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月6日(星期二) 下午5:05
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[cym1102/nginxWebUI] 怎么迁移证书? (Issue #59)





 
目前备份配置, 不包含证书.
 
目前方案是重新申请一次证书,  比较麻烦,  能包含在备份配置里吗?

**Comment by cym1102** [comment]
你要迁移数据, 直接迁移/home/nginxWebUI/文件夹到新服务器即可, 一切证书用户密码全在里面, 页面上的备份还原功能是有局限性的, 不是到处都可用.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月6日(星期二) 下午5:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cym1102/nginxWebUI] 怎么迁移证书? (Issue #59)





 
还有 那个二次密码验证  也不包含在备份好像,   这样的话 备份似乎不能用于迁移数据了 .
 
考虑下, 开发个其他方案呢?

**Comment by cym1102** [comment]
防止你改错东西了想改回来找不到历史记录



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月6日(星期二) 下午5:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cym1102/nginxWebUI] 怎么迁移证书? (Issue #59)





 
也行, 直接拷贝把.
 所以好奇备份功能的场景是啥
