### ISSUE TITLE
建议启用配置那里能否做成重启nginx

### ISSUE THREAD

**Issue by soartou** [cym1102/nginxWebUI#61]
现在分成两个步骤，好像不能代理管理

**Comment by cym1102** [comment]
重载就是基本等于重启



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月16日(星期五) 凌晨1:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [cym1102/nginxWebUI] 建议启用配置那里能否做成重启nginx (Issue #61)





 
现在分成两个步骤，好像不能代理管理
