### ISSUE TITLE
登录界面乱码

### ISSUE THREAD

**Issue by Merdou** [cym1102/nginxWebUI#62]
登录界面解码，启动命令 java -jar nginxWebUI-3.4.6.jar
![image](https://user-images.githubusercontent.com/51307737/208064145-96ebc5e6-ab98-40ad-8dd2-184cdca41022.png)

**Comment by cym1102** [comment]
少了一个启动参数&nbsp;java -jar -Dfile.encoding=UTF-8 D:/home/nginxWebUI/nginxWebUI.jar
