### ISSUE TITLE
What an amazing project, wow

### ISSUE THREAD

**Issue by matheusmaiberg** [cym1102/nginxWebUI#63]
Kudos to you my friend, this is such a masterpiece that i dont know why this is not mostly used yet.

I think the problem is that mostly users of nginx and programmers (my humble guess, i could be wrong) uses English language, so the page with chinese language and prints makes them go away, and in the docummentation still not up the top, YET.

But this project deserves so much more attention, im amazed.

Thank you @cym1102 for the time and effort putted in this project to make this masterpiece.

**Comment by Paxton0222** [comment]
Maybe we can translate this project's documention to english, let more programmers know about this project.

**Comment by cym1102** [comment]
I have english document



---Original---
From: ***@***.***&gt;
Date: Wed, Jan 11, 2023 00:22 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cym1102/nginxWebUI] What an amazing project, wow (Issue #63)




 
Maybe we can translate this project's documention to english, let more programmers know about this project.
