### ISSUE TITLE
前端

### ISSUE THREAD

**Issue by nathangary** [cym1102/nginxWebUI#67]
你好，前端是否可以开源？

**Comment by cym1102** [comment]
前端是layui本来就是开源的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月23日(周四) 晚上6:22
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cym1102/nginxWebUI] 前端 (Issue #67)




 
你好，前端是否可以开源？
