### ISSUE TITLE
如何支持源码安装的nginx

### ISSUE THREAD

**Issue by atobe-kegio** [cym1102/nginxWebUI#68]

**Comment by cym1102** [comment]
初始化的时候,有选择你的nginx是源码安装还是apt yum安装




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cym1102/nginxWebUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月27日(星期一) 上午8:51
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[cym1102/nginxWebUI] 如何支持源码安装的nginx (Issue #68)
