### ISSUE TITLE
你好，请问反向代理能否增加对ipv6的监听

### ISSUE THREAD

**Issue by gfgjs** [cym1102/nginxWebUI#69]
现在需要手动在conf中添加 listen [::] ，但刷新页面就会丢失添加

**Comment by cym1102** [comment]
监听ip那里本来就支持监听ipv6




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cym1102/nginxWebUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月1日(星期三) 凌晨0:23
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[cym1102/nginxWebUI] 你好，请问反向代理能否增加对ipv6的监听 (Issue #69)

**Comment by gfgjs** [comment]
感谢您，看到了

**Comment by Dot233** [comment]
监听端口填写::以后，nginx就不监听ipv4了，双栈监听的话配置文件需要写两行监听，可以在UI那里加一个按钮方便进行双栈监听吗？
我现在是创建了一个listen [::]:80的参数模板然后应用到所有反向代理上

**Comment by cym1102** [comment]
你可以添加额外参数方式实现



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月26日(周六) 下午5:00
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [cym1102/nginxWebUI] 你好，请问反向代理能否增加对ipv6的监听 (Issue #69)




 
监听端口填写::以后，nginx就不监听ipv4了，双栈监听的话配置文件需要写两行监听，可以在UI那里加一个按钮方便进行双栈监听吗？
 我现在是创建了一个listen [::]:80的参数模板然后应用到所有反向代理上
