### ISSUE TITLE
麻烦支持一下Let's Encrypt证书及自动续订

### ISSUE THREAD

**Issue by huyuanjing** [cym1102/nginxWebUI#7]
。。。

**Comment by cym1102** [comment]
现在不就支持吗？lets的证书和续签都支持，看看证书管理那里



---原始邮件---
发件人: "胡远晶"<notifications@github.com&gt;
发送时间: 2020年12月9日(周三) 下午4:39
收件人: "cym1102/nginxWebUI"<nginxWebUI@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [cym1102/nginxWebUI] 麻烦支持一下Let's Encrypt证书及自动续订 (#7)




 
。。。
