### ISSUE TITLE
[建议] 以文件形式存储参数模板并以include形式引用

### ISSUE THREAD

**Issue by GOUKOU007** [cym1102/nginxWebUI#70]
### 当前行为
添加的参数模板似乎并没有以文件形式存储在目录中，而是放在数据库里？如果只是我没有找到，我建议将对应文件放入/home/nginxWebUI目录下以实现docker部署时的配置持久化。
### 期望行为
添加的参数模板以`模板名.conf`的形式存储在/home/nginxWebUI/templates之类的目录下，并在nginx.conf中以include的方式引用。
### 原因
相比添加单个参数的需求，一次性添加多个参数或location块的情况会更多。在当前行为下以输入“名称、值”的方式配置一组参数非常麻烦，我目前使用的方法是直接在“值”中输入所有需要配置的参数或location，如：
```
location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$ {
    expires      30d;
}
location ~ .*\.(js|css)?$ {
    expires      12h;
}
location ~ /.well-known {
    allow all;
}
```
或者
```
gzip on;
gzip_min_length  1k;
gzip_buffers     4 16k;
gzip_http_version 1.1;
gzip_comp_level 2;
gzip_types     text/plain application/javascript application/x-javascript text/javascript text/css application/xml application/xml+rss;
gzip_vary on;
gzip_proxied   expired no-cache no-store private auth;
gzip_disable   "MSIE [1-6]\.";
```
而这种方法与输入“键、值”配置模板的逻辑是不符的。

因此，不如直接使用include方式对生成的模板文件进行引用。例如我创建了名为{template_name}的模板，则在模板文件夹如/home/nginxWebUI/templates下自动生成{template_name}.conf。插入参数的行为替换为在对应的.conf文件中以include的形式插入{template_name}.conf。

**Comment by cym1102** [comment]
不好意思, 本项目所有的conf都是通过数据库配置生成出来的, 现在改为本地存储无法实现, 改动太大
