### ISSUE TITLE
【建议】能否增加webdav的支持

### ISSUE THREAD

**Issue by s44151060** [cym1102/nginxWebUI#71]
作者你好！目前镜像里自带的nginx好像没有添加webdav的模块，反向代理webdav只可以读取nas中的文件，却无法修改，能否添加支持，谢谢！

**Comment by cym1102** [comment]
这个你可以进入docker容器中的alpine系统使用apk add来添加nginx的模块




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月22日(星期三) 中午12:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [cym1102/nginxWebUI] 【建议】能否增加webdav的支持 (Issue #71)





 
作者你好！目前镜像里自带的nginx好像没有添加webdav的模块，反向代理webdav只可以读取nas中的文件，却无法修改，能否添加支持，谢谢！

**Comment by s44151060** [comment]
感谢回复，按照您提供的方法，已经搞定了，谢谢！
