### ISSUE TITLE
Windows下，jar起不来。

### ISSUE THREAD

**Issue by DJonesT** [cym1102/nginxWebUI#73]
已经遵照README，安装JDK，系统环境变量，打指令后的LOG如下（错误提示）：

ERROR 2023-03-26 19:02:31.668 [-main][*][com.cym.NginxWebUI]: 
Unsupported class file major version 64
java.lang.IllegalArgumentException: Unsupported class file major version 64

ERROR 2023-03-26 19:07:59.858 [-main][*][com.cym.NginxWebUI]: 
Illegal exception table range in class file com/cym/service/$Proxy_LocationService
java.lang.ClassFormatError: Illegal exception table range in class file com/cym/service/$Proxy_LocationService

是不是JDK版本太高？JDK20，还请赐教。

**Comment by cym1102** [comment]
版本太高，换jdk1.8吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月26日(周日) 晚上7:11
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cym1102/nginxWebUI] Windows下，jar起不来。 (Issue #73)




 
已经遵照README，安装JDK，系统环境变量，打指令后的LOG如下（错误提示）：
 
ERROR 2023-03-26 19:02:31.668 [-main][*][com.cym.NginxWebUI]:
 Unsupported class file major version 64
 java.lang.IllegalArgumentException: Unsupported class file major version 64
 
ERROR 2023-03-26 19:07:59.858 [-main][*][com.cym.NginxWebUI]:
 Illegal exception table range in class file com/cym/service/$Proxy_LocationService
 java.lang.ClassFormatError: Illegal exception table range in class file com/cym/service/$Proxy_LocationService
 
是不是JDK版本太高？JDK20，还请赐教。
