### ISSUE TITLE
启动参数设置的-Xmx64m

### ISSUE THREAD

**Issue by harvies** [cym1102/nginxWebUI#75]
是不是太小了，启动特别慢，要几分钟

**Comment by cym1102** [comment]
现在新版本一般不用这个参数了，让它自己分配内存



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月11日(周二) 晚上10:00
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cym1102/nginxWebUI] 启动参数设置的-Xmx64m (Issue #75)




 
是不是太小了，启动特别慢，要几分钟

**Comment by harvies** [comment]
![image](https://github.com/cym1102/nginxWebUI/assets/16585330/b217df89-ce63-4655-9774-bff85f992880)

**Comment by harvies** [comment]
cpu 100%
