### ISSUE TITLE
关于方向代理配置启用ssl

### ISSUE THREAD

**Issue by JCYFeng** [cym1102/nginxWebUI#76]
尝试在一个Server中监听80，然后开启ssl，强制跳转至443的配置，发现生成的配置文件有误。
为listen 80 ssl；
![微信截图_20230413170718](https://user-images.githubusercontent.com/38749885/231711338-04143275-5f70-4425-9117-1b28ad8f8e1b.png)

**Comment by cym1102** [comment]
你监听端口没写443



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月13日(周四) 下午5:08
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cym1102/nginxWebUI] 关于方向代理配置启用ssl (Issue #76)




 
尝试在一个Server中监听80，然后开启ssl，强制跳转至443的配置，发现生成的配置文件有误。
 为listen 80 ssl；

**Comment by JCYFeng** [comment]
如果监听端口写443，那么在http跳https这里怎么填？
![微信截图_20230413172629](https://user-images.githubusercontent.com/38749885/231716398-681db98a-e63d-44b2-9f9c-57a90ca2aa67.png)

**Comment by JCYFeng** [comment]
了解了，但是这样的话，就看起来怪怪的，不过在配置文件上是对的。
