### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by jimsoft1000** [cym1102/nginxWebUI#77]
建议增加主文件分拆多个子文件的配置模式 include /etc/nginx/conf.d/*.conf

**Comment by cym1102** [comment]
现在就有啊



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月19日(周三) 晚上6:16
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cym1102/nginxWebUI] 功能建议 (Issue #77)




 
建议增加主文件分拆多个子文件的配置模式 include /etc/nginx/conf.d/*.conf

**Comment by jimsoft1000** [comment]
> 现在就有啊
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年4月19日(周三) 晚上6:16 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [cym1102/nginxWebUI] 功能建议 (Issue #77) 建议增加主文件分拆多个子文件的配置模式 include /etc/nginx/conf.d/*.conf — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

我找到了，按域名拆分文件，这个开始我没注意看，感谢，工具很强大
