### ISSUE TITLE
怎么在windows 上使用, 有没有相关教程

### ISSUE THREAD

**Issue by yizems** [cym1102/nginxWebUI#8]

**Comment by cym1102** [comment]
和linux差不多，把jar运行起来就行了



---原始邮件---
发件人: "YiZe"<notifications@github.com&gt;
发送时间: 2020年12月21日(周一) 中午1:42
收件人: "cym1102/nginxWebUI"<nginxWebUI@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [cym1102/nginxWebUI] 怎么在windows 上使用, 有没有相关教程 (#8)

**Comment by yizems** [comment]
我刚才设置有个问题, 就是我本机是有nginx 的, 但是 没有读出来已经有的配置, 是需要在平台上重新配置下么

**Comment by yizems** [comment]
还有就是是否可以设置每台机器的nginx 目录

**Comment by cym1102** [comment]
当然可以



---原始邮件---
发件人: "YiZe"<notifications@github.com&gt;
发送时间: 2020年12月21日(周一) 下午3:25
收件人: "cym1102/nginxWebUI"<nginxWebUI@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"cym1102"<cym1102@qq.com&gt;;
主题: Re: [cym1102/nginxWebUI] 怎么在windows 上使用, 有没有相关教程 (#8)




 
还有就是是否可以设置每台机器的nginx 目录

**Comment by cym1102** [comment]
本项目不读取已有配置，只根据数据库生成新的配置文件



---原始邮件---
发件人: "YiZe"<notifications@github.com&gt;
发送时间: 2020年12月21日(周一) 下午3:25
收件人: "cym1102/nginxWebUI"<nginxWebUI@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"cym1102"<cym1102@qq.com&gt;;
主题: Re: [cym1102/nginxWebUI] 怎么在windows 上使用, 有没有相关教程 (#8)




 
我刚才设置有个问题, 就是我本机是有nginx 的, 但是 没有读出来已经有的配置, 是需要在平台上重新配置下么

**Comment by yizems** [comment]
ok ,3Q , 我试试
