### ISSUE TITLE
二级域名申请证书失败

### ISSUE THREAD

**Issue by chenxudong2020** [cym1102/nginxWebUI#81]
/home/nginxWebUI/.acme.sh/acme.sh --issue --force --dns dns_dp -d www.dubux.ltd --server letsencrypt
申请失败
[Wed May 17 09:15:58 CST 2023] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Wed May 17 09:15:58 CST 2023] Creating domain key
[Wed May 17 09:15:58 CST 2023] The domain key is here: /home/nginxWebUI/.acme.sh//www.dubux.ltd/www.dubux.ltd.key
[Wed May 17 09:15:58 CST 2023] Single domain='www.dubux.ltd'
[Wed May 17 09:15:58 CST 2023] Getting domain auth token for each domain
[Wed May 17 09:16:02 CST 2023] Getting webroot for domain='www.dubux.ltd'
[Wed May 17 09:16:02 CST 2023] Adding txt value: Z9uzOhGILCwsVVGcImXijF66TPYmb8j-0yrFTGgV4-0 for domain: _acme-challenge.www.dubux.ltd
[Wed May 17 09:16:02 CST 2023] Adding record
[Wed May 17 09:16:02 CST 2023] The txt record is added: Success.
[Wed May 17 09:16:02 CST 2023] Let's check each DNS record now. Sleep 20 seconds first.
[Wed May 17 09:16:22 CST 2023] You can use '--dnssleep' to disable public dns checks.
[Wed May 17 09:16:22 CST 2023] See: https://github.com/acmesh-official/acme.sh/wiki/dnscheck
[Wed May 17 09:16:22 CST 2023] Checking www.dubux.ltd for _acme-challenge.www.dubux.ltd
[Wed May 17 09:16:24 CST 2023] Domain www.dubux.ltd '_acme-challenge.www.dubux.ltd' success.
[Wed May 17 09:16:24 CST 2023] All success, let's return
[Wed May 17 09:16:24 CST 2023] Verifying: www.dubux.ltd
[Wed May 17 09:16:25 CST 2023] Pending, The CA is processing your order, please just wait. (1/30)
[Wed May 17 09:16:28 CST 2023] Removing DNS records.
[Wed May 17 09:16:28 CST 2023] Removing txt: Z9uzOhGILCwsVVGcImXijF66TPYmb8j-0yrFTGgV4-0 for domain: _acme-challenge.www.dubux.ltd
[Wed May 17 09:16:29 CST 2023] Removed: Success

主域名dubux.ltd托管到了dnspod

**Comment by cym1102** [comment]
腾讯的dns申请证书一直有问题, 更新acme.sh版本也没效果




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月17日(星期三) 上午9:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [cym1102/nginxWebUI] 二级域名申请证书失败 (Issue #81)





 
/home/nginxWebUI/.acme.sh/acme.sh --issue --force --dns dns_dp -d www.dubux.ltd --server letsencrypt
 申请失败
 [Wed May 17 09:15:58 CST 2023] Using CA: https://acme-v02.api.letsencrypt.org/directory
 [Wed May 17 09:15:58 CST 2023] Creating domain key
 [Wed May 17 09:15:58 CST 2023] The domain key is here: /home/nginxWebUI/.acme.sh//www.dubux.ltd/www.dubux.ltd.key
 [Wed May 17 09:15:58 CST 2023] Single domain='www.dubux.ltd'
 [Wed May 17 09:15:58 CST 2023] Getting domain auth token for each domain
 [Wed May 17 09:16:02 CST 2023] Getting webroot for domain='www.dubux.ltd'
 [Wed May 17 09:16:02 CST 2023] Adding txt value: Z9uzOhGILCwsVVGcImXijF66TPYmb8j-0yrFTGgV4-0 for domain: _acme-challenge.www.dubux.ltd
 [Wed May 17 09:16:02 CST 2023] Adding record
 [Wed May 17 09:16:02 CST 2023] The txt record is added: Success.
 [Wed May 17 09:16:02 CST 2023] Let's check each DNS record now. Sleep 20 seconds first.
 [Wed May 17 09:16:22 CST 2023] You can use '--dnssleep' to disable public dns checks.
 [Wed May 17 09:16:22 CST 2023] See: https://github.com/acmesh-official/acme.sh/wiki/dnscheck
 [Wed May 17 09:16:22 CST 2023] Checking www.dubux.ltd for _acme-challenge.www.dubux.ltd
 [Wed May 17 09:16:24 CST 2023] Domain www.dubux.ltd '_acme-challenge.www.dubux.ltd' success.
 [Wed May 17 09:16:24 CST 2023] All success, let's return
 [Wed May 17 09:16:24 CST 2023] Verifying: www.dubux.ltd
 [Wed May 17 09:16:25 CST 2023] Pending, The CA is processing your order, please just wait. (1/30)
 [Wed May 17 09:16:28 CST 2023] Removing DNS records.
 [Wed May 17 09:16:28 CST 2023] Removing txt: Z9uzOhGILCwsVVGcImXijF66TPYmb8j-0yrFTGgV4-0 for domain: _acme-challenge.www.dubux.ltd
 [Wed May 17 09:16:29 CST 2023] Removed: Success
 
主域名dubux.ltd托管到了dnspod
