### ISSUE TITLE
非常好用的webui，再给一个定期导出配置的建议！

### ISSUE THREAD

**Issue by v808comd** [cym1102/nginxWebUI#82]
非常赞，大大简化了web管理员的工作量，我还想建议您增加一个自动配置导出的功能，比如定时将配置导出并发送到邮箱。这样作为管理员的我就更轻松了。有点自私，呵呵！

**Comment by cym1102** [comment]
暂时没有相应计划

**Comment by v808comd** [comment]
加上计划吧。定期备份是网络管理员都十分期待的功能。
