### ISSUE TITLE
nginxwebui增加修改baseurl的支持

### ISSUE THREAD

**Issue by DJBoy520** [cym1102/nginxWebUI#85]
nginxwebui搭建起来了，也申请了证书，nginxwebui的http界面在监听8080端口。

我服务器上有很多服务，均希望通过nginxwebui进行https的代理，流量分发想要只监听一个443端口，然后通过后缀的形式，进行流量分发。比如https://127.0.0.1/nginxwebui，https://12.0.0.1/other.....这样的形式。

但现在出现了问题，https://127.0.0.1/nginxwebui这样加了后缀，但是nginxwebui这个项目的baseurl没有加后缀，导致访问不到资源，目前也没能在官方文档里，看见项目对修改baseurl的支持。

服务器是在内网里，想通过端口映射映射到外网，pull端口的时候想尽可能只pull一个端口出去，就产生了这个需求。

请问这个功能本项目有么，如果没有的话会考虑加不。

**Comment by cym1102** [comment]
这个系统是类springboot框架, 没法做成子域名的形式
