### ISSUE TITLE
远程命令漏洞

### ISSUE THREAD

**Issue by alansun2** [cym1102/nginxWebUI#87]
执行以下命令：
```
http://xxxxxx/AdminPage/conf/runCmd?cmd=ifconfig
```

版本: 3.2.9

请求这个 runCmd 可以关闭吗？

**Comment by cym1102** [comment]
升级到最新版已解决此问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月30日(星期五) 上午8:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [cym1102/nginxWebUI] 远程命令漏洞 (Issue #87)





 
执行以下命令：
 http://xxxxxx/AdminPage/conf/runCmd?cmd=ifconfig  
版本: 3.2.9

**Comment by alansun2** [comment]
好的

**Comment by XYZliang** [comment]
> 升级到最新版已解决此问题
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年6月30日(星期五) 上午8:50 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [cym1102/nginxWebUI] 远程命令漏洞 (Issue #87) 执行以下命令： http://xxxxxx/AdminPage/conf/runCmd?cmd=ifconfig 版本: 3.2.9 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

搞得我服务器被入侵。。。。

**Comment by 376924098** [comment]
破案了

**Comment by XYZliang** [comment]
> 破案了

而且还docker逃逸，干我主机去了，还有权限维持，只能重装

**Comment by 376924098** [comment]
> 

折腾两天  昨晚备份数据 折腾到1点多

**Comment by XYZliang** [comment]
> > 
> 
> 折腾两天 昨晚备份数据 折腾到1点多

真的服了
