### ISSUE TITLE
关于PVE LXC部署时cpu核心获取的问题

### ISSUE THREAD

**Issue by chenhong3333** [cym1102/nginxWebUI#88]
LXC特权容器部署，CPU核心显示为1，不能显示实际核心数（虚拟机部署正常）

lxc相关的参数如下：
ostype: debian
features: nesting=1
lxc.apparmor.profile: unconfined
lxc.cgroup.devices.allow: a
lxc.cap.drop:

**Comment by chenhong3333** [comment]
补充：容器内通过lscpu能获取到正确核心数

**Comment by cym1102** [comment]
这个没法，我这边只考虑传统环境



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月30日(周五) 晚上6:32
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cym1102/nginxWebUI] 关于PVE LXC部署时cpu核心获取的问题 (Issue #88)




 
LXC特权容器部署，CPU核心显示为1，不能显示实际核心数（虚拟机部署正常）
 
lxc相关的参数如下：
 ostype: debian
 features: nesting=1
 lxc.apparmor.profile: unconfined
 lxc.cgroup.devices.allow: a
 lxc.cap.drop:

**Comment by chenhong3333** [comment]
了解，谢谢！
