### ISSUE TITLE
反向代理报400: Bad Request

### ISSUE THREAD

**Issue by xiangchu95** [cym1102/nginxWebUI#89]
配置反向代理是偶发400错误, 我一共部署了4个反向代理,其他3个都是正常的, 只有lot.xiangchu.tk 这个域名的反向代理报400错误,这个是我的配置文件 麻烦协助帮忙看一下 不胜感谢

这个是我启动docker的日志 有个警告不知道是不是因为这个导致的  
nginxWebUI 3.6.4

INFO  2023-07-01 23:52:12.838 [-main][*][o.noear.solon.Solon]: 
App: End loading elapsed=10789ms pid=7 v=2.3.3
WARN  2023-07-01 23:52:34.432 [-XNIO-1 task-1][*][o.s.o.l.LinuxOperatingSystem]: 
Did not find udev library in operating system. Some features may not work.

以下是配置文件:
load_module /usr/lib/nginx/modules/ngx_stream_module.so;
worker_processes auto;
events {
    worker_connections  1024;
    accept_mutex on;
  }
http {
  include mime.types;
  default_type application/octet-stream;
  keepalive_timeout 75s;
  gzip on;
  gzip_min_length 4k;
  gzip_comp_level 4;
  client_max_body_size 2048m;
  client_header_buffer_size 32k;
  client_body_buffer_size 8m;
  server_names_hash_bucket_size 512;
  proxy_headers_hash_max_size 51200;
  proxy_headers_hash_bucket_size 6400;
  gzip_types application/javascript application/x-javascript text/javascript text/css application/json application/xml;
  error_log /home/nginxWebUI/log/error.log;
  map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
  }
  access_log /home/nginxWebUI/log/access.log;
  include /home/nginxWebUI/conf.d/adm.xiangchu.tk.conf;
  include /home/nginxWebUI/conf.d/frps.xiangchu.tk.conf;
  include /home/nginxWebUI/conf.d/lot.xiangchu.tk.conf;
  include /home/nginxWebUI/conf.d/db.xiangchu.tk.conf;
}

server {
  #内网穿透-MBPP-homeAssistant;
  server_name lot.xiangchu.tk;
  listen 443 ssl http2;
  ssl_certificate /home/nginxWebUI/.acme.sh/*.xiangchu.tk/fullchain.cer;
  ssl_certificate_key /home/nginxWebUI/.acme.sh/*.xiangchu.tk/*.xiangchu.tk.key;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
  if ($scheme = http) {
    return 301 https://$host:443$request_uri;
  }
  location / {
    proxy_pass http://127.0.0.1:7911;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_redirect http:// https://;
  }
}

**Comment by cym1102** [comment]
看不出来有什么问题，一切配置都是标准化的，可能是你的程序服务有问题，docker报的也只是警告，不是错误。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月2日(周日) 中午11:09
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cym1102/nginxWebUI] 反向代理报400: Bad Request (Issue #89)




 
配置反向代理是偶发400错误, 我一共部署了4个反向代理,其他3个都是正常的, 只有lot.xiangchu.tk 这个域名的反向代理报400错误,这个是我的配置文件 麻烦协助帮忙看一下 不胜感谢
 
这个是我启动docker的日志 有个警告不知道是不是因为这个导致的
 nginxWebUI 3.6.4
 
INFO  2023-07-01 23:52:12.838 [-main][][o.noear.solon.Solon]:
 App: End loading elapsed=10789ms pid=7 v=2.3.3
 WARN  2023-07-01 23:52:34.432 [-XNIO-1 task-1][][o.s.o.l.LinuxOperatingSystem]:
 Did not find udev library in operating system. Some features may not work.
 
以下是配置文件:
 load_module /usr/lib/nginx/modules/ngx_stream_module.so;
 worker_processes auto;
 events {
 worker_connections  1024;
 accept_mutex on;
 }
 http {
 include mime.types;
 default_type application/octet-stream;
 keepalive_timeout 75s;
 gzip on;
 gzip_min_length 4k;
 gzip_comp_level 4;
 client_max_body_size 2048m;
 client_header_buffer_size 32k;
 client_body_buffer_size 8m;
 server_names_hash_bucket_size 512;
 proxy_headers_hash_max_size 51200;
 proxy_headers_hash_bucket_size 6400;
 gzip_types application/javascript application/x-javascript text/javascript text/css application/json application/xml;
 error_log /home/nginxWebUI/log/error.log;
 map $http_upgrade $connection_upgrade {
 default upgrade;
 '' close;
 }
 access_log /home/nginxWebUI/log/access.log;
 include /home/nginxWebUI/conf.d/adm.xiangchu.tk.conf;
 include /home/nginxWebUI/conf.d/frps.xiangchu.tk.conf;
 include /home/nginxWebUI/conf.d/lot.xiangchu.tk.conf;
 include /home/nginxWebUI/conf.d/db.xiangchu.tk.conf;
 }
 
server {
 
内网穿透-MBPP-homeAssistant;
 
server_name lot.xiangchu.tk;
 listen 443 ssl http2;
 ssl_certificate /home/nginxWebUI/.acme.sh/.xiangchu.tk/fullchain.cer;
 ssl_certificate_key /home/nginxWebUI/.acme.sh/.xiangchu.tk/*.xiangchu.tk.key;
 ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
 if ($scheme = http) {
 return 301 https://$host:443$request_uri;
 }
 location / {
 proxy_pass http://127.0.0.1:7911;
 proxy_set_header Host $host;
 proxy_set_header X-Real-IP $remote_addr;
 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
 proxy_set_header X-Forwarded-Host $http_host;
 proxy_set_header X-Forwarded-Port $server_port;
 proxy_set_header X-Forwarded-Proto $scheme;
 proxy_redirect http:// https://;
 }
 }

**Comment by xiangchu95** [comment]
是的 我也没看出配置有啥问题 我通过ip+端口形式也可以访问 通过反向代理后就会报400错误.而且只有这一个服务会报400错误 其他服务也都是正常的

**Comment by xiangchu95** [comment]
我从网上看到这么个原因导致的400错误 不知道是不是因为这个导致的 麻烦帮忙看下
<img width="1013" alt="image" src="https://github.com/cym1102/nginxWebUI/assets/110237853/f2307d66-32fb-4f1c-ad0d-761170eda04c">

**Comment by cym1102** [comment]
不是这个漏洞



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月2日(周日) 中午11:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cym1102/nginxWebUI] 反向代理报400: Bad Request (Issue #89)




 
我从网上看到这么个原因导致的400错误 不知道是不是因为这个导致的 麻烦帮忙看下
