### ISSUE TITLE
docker版本lua问题

### ISSUE THREAD

**Issue by yyf-ytt** [cym1102/nginxWebUI#92]
你好，现在docker版本中可以使用lua吗？
nginx -v中我看到了lua模块，但使用时候报错。
`    location /aaa {
      default_type 'text/plain';
      content_by_lua_block {
             ngx.say('Hello,world!')
           }
    }
`

**unknown directive "content_by_lua"**

**Comment by cym1102** [comment]
这个不太懂，我用的alpine默认的nginx



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月26日(周三) 晚上6:30
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cym1102/nginxWebUI] docker版本lua问题 (Issue #92)




 
你好，现在docker版本中可以使用lua吗？
 nginx -v中我看到了lua模块，但使用时候报错。
    location /aaa { default_type 'text/plain'; content_by_lua_block { ngx.say('Hello,world!') } }
 
unknown directive "content_by_lua"

**Comment by yyf-ytt** [comment]
哦哦。明白了。那我再看看，感谢
