### ISSUE TITLE
runCmd接口依然还存在命令注入漏洞

### ISSUE THREAD

**Issue by chensongkui** [cym1102/nginxWebUI#93]
runCmd接口依然还存在命令注入漏洞，比如给runCmd接口传入/bin/sh -c reboot命令就可以使服务挂掉

**Comment by cym1102** [comment]
基本上都是要登录才能调用这个接口, 而且确实没法完全限制命令的调用




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月27日(星期四) 上午9:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [cym1102/nginxWebUI] runCmd接口依然还存在命令注入漏洞 (Issue #93)





 
runCmd接口依然还存在命令注入漏洞，比如给runCmd接口传入/bin/sh -c reboot命令就可以使服务挂掉
