### ISSUE TITLE
upsteam负载监控无法发送通知邮件

### ISSUE THREAD

**Issue by chenhong3333** [cym1102/nginxWebUI#94]
同样的国内163/QQ邮箱配置，nginx监控服务可以成功发送邮件，负载监控页面无法成功发送，点击测试发送显示：“出错了，请联系开发者”

**Comment by cym1102** [comment]
下个版本更新

**Comment by Lizhen0628** [comment]
还有报错: Could not connect to SMTP host: smtp.gmail.com, port: 587

**Comment by cym1102** [comment]
检查一样邮箱那边确实开通了没有，协议有没有搞对



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月16日(周日) 凌晨2:13
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [cym1102/nginxWebUI] upsteam负载监控无法发送通知邮件 (Issue #94)




 
还有报错: Could not connect to SMTP host: smtp.gmail.com, port: 587
