### ISSUE TITLE
新版本无法运行，直接崩溃：siginto: EXCEPTION ACCESS VIOLATION (0xc0000005), writing address Ox0000000000000000

### ISSUE THREAD

**Issue by XYZliang** [cym1102/nginxWebUI#95]
如题，因为近期runcmd漏洞的影响，我将我一台服务器上的nginxwebui从3.1.6进行升级。我测试了最新的3.6.9（官网最新）以及3.6.3（github最新），在运行jar文件后直接崩溃，并留下了mdmp和log文件。
相关文件如下：
[hs_err_pid44252.log](https://github.com/cym1102/nginxWebUI/files/12256800/hs_err_pid44252.log)
[hs_err_pid44252.mdmp](https://d.kstore.space/download/2078/hs_err_pid44252.mdmp)
经测试github上另一可下载的较旧版本3.4.6可以正常运行。（3.5.x因为无法下载没法测试）

**Comment by XYZliang** [comment]
系统环境：
Windows server2022 21h2 20348.617
JDK 17.0.1
运行命令：
![image](https://github.com/cym1102/nginxWebUI/assets/59312540/f99ffbcc-8f51-4229-8679-fedc261ba85f)

**Comment by cym1102** [comment]
我不知道你是怎么启动的, 我启动3.6.9是可以正常运行的







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月4日(星期五) 中午11:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [cym1102/nginxWebUI] 新版本无法运行，直接崩溃：siginto: EXCEPTION ACCESS VIOLATION (0xc0000005), writing address Ox0000000000000000 (Issue #95)





 
如题，因为近期runcmd漏洞的影响，我计算将我一台服务器上的nginxwebui从3.1.6。我测试了最新的3.6.9（官网最新）以及3.6.3（github最新），在运行jar文件后直接崩溃，并留下了mdmp和log文件。
 相关文件如下：
 hs_err_pid44252.log
 hs_err_pid44252.mdmp
 经测试github上另一可下载的较旧版本3.4.6可以正常运行。（3.5.x因为无法下载没法测试）

**Comment by XYZliang** [comment]
> 我不知道你是怎么启动的, 我启动3.6.9是可以正常运行的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年8月4日(星期五) 中午11:49 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [cym1102/nginxWebUI] 新版本无法运行，直接崩溃：siginto: EXCEPTION ACCESS VIOLATION (0xc0000005), writing address Ox0000000000000000 (Issue #95) 如题，因为近期runcmd漏洞的影响，我计算将我一台服务器上的nginxwebui从3.1.6。我测试了最新的3.6.9（官网最新）以及3.6.3（github最新），在运行jar文件后直接崩溃，并留下了mdmp和log文件。 相关文件如下： hs_err_pid44252.log hs_err_pid44252.mdmp 经测试github上另一可下载的较旧版本3.4.6可以正常运行。（3.5.x因为无法下载没法测试） — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

刚刚上传了相关环境和运行命令，可以看看

**Comment by XYZliang** [comment]
> 我不知道你是怎么启动的, 我启动3.6.9是可以正常运行的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年8月4日(星期五) 中午11:49 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [cym1102/nginxWebUI] 新版本无法运行，直接崩溃：siginto: EXCEPTION ACCESS VIOLATION (0xc0000005), writing address Ox0000000000000000 (Issue #95) 如题，因为近期runcmd漏洞的影响，我计算将我一台服务器上的nginxwebui从3.1.6。我测试了最新的3.6.9（官网最新）以及3.6.3（github最新），在运行jar文件后直接崩溃，并留下了mdmp和log文件。 相关文件如下： hs_err_pid44252.log hs_err_pid44252.mdmp 经测试github上另一可下载的较旧版本3.4.6可以正常运行。（3.5.x因为无法下载没法测试） — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

另一个ubuntu服务器用的是docker的3.6.9没问题
