### ISSUE TITLE
管理平台是否可以使用https协议

### ISSUE THREAD

**Issue by db-root** [cym1102/nginxWebUI#99]
你好，我是用jar包运行的管理平台，默认的地址是http://IP:8080为访问地址，请问是否可以支持https协议，例如https://IP:8080这样的访问方式

**Comment by cym1102** [comment]
可以, 只要你用nginx代理添加证书就行




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cym1102/nginxWebUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月14日(星期一) 中午11:17
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[cym1102/nginxWebUI] 管理平台是否可以使用https协议 (Issue #99)





 
你好，我是用jar包运行的管理平台，默认的地址是http://IP:8080为访问地址，请问是否可以支持https协议，例如https://IP:8080这样的访问方式

**Comment by db-root** [comment]
我的意思是管理平台地址访问。管理平台现在nohup java -jar -Dfile.encoding=UTF-8 /home/nginxWebUI/nginxWebUI.jar --server.port=8080 --project.home=/home/nginxWebUI/ > /dev/null &启动之后的访问地址是http的嘛，有没有参数可以使用https的，我不是说管理平台代理https之类的问题。
这样描述可以理解吗

**Comment by cym1102** [comment]
目前没有直接支持https的功能




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月14日(星期一) 中午11:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cym1102/nginxWebUI] 管理平台是否可以使用https协议 (Issue #99)





 
我的意思是管理平台地址访问。管理平台现在nohup java -jar -Dfile.encoding=UTF-8 /home/nginxWebUI/nginxWebUI.jar --server.port=8080 --project.home=/home/nginxWebUI/ &gt; /dev/null &amp;启动之后的访问地址是http的嘛，有没有参数可以使用https的，我不是说管理平台代理https之类的问题。
 这样描述可以理解吗
